declare -x AZ_BATCH_ACCOUNT_NAME="exp1hildebatch"
declare -x AZ_BATCH_ACCOUNT_URL="https://exp1hildebatch.southeastasia.batch.azure.com/"
declare -x AZ_BATCH_CERTIFICATES_DIR="/mnt/batch/tasks/workitems/random_forest/job-1/task-00028/certs"
declare -x AZ_BATCH_JOB_ID="random_forest"
declare -x AZ_BATCH_JOB_PREP_DIR="/mnt/batch/tasks/workitems/random_forest/job-1/jobpreparation"
declare -x AZ_BATCH_JOB_PREP_WORKING_DIR="/mnt/batch/tasks/workitems/random_forest/job-1/jobpreparation/wd"
declare -x AZ_BATCH_NODE_ID="tvm-2112069986_6-20180411t200903z"
declare -x AZ_BATCH_NODE_IS_DEDICATED="true"
declare -x AZ_BATCH_NODE_ROOT_DIR="/mnt/batch/tasks"
declare -x AZ_BATCH_NODE_SHARED_DIR="/mnt/batch/tasks/shared"
declare -x AZ_BATCH_NODE_STARTUP_DIR="/mnt/batch/tasks/startup"
declare -x AZ_BATCH_POOL_ID="experiment"
declare -x AZ_BATCH_TASK_DIR="/mnt/batch/tasks/workitems/random_forest/job-1/task-00028"
declare -x AZ_BATCH_TASK_ID="task-00028"
declare -x AZ_BATCH_TASK_USER="_azbatch"
declare -x AZ_BATCH_TASK_USER_IDENTITY="PoolAdmin"
declare -x AZ_BATCH_TASK_WORKING_DIR="/mnt/batch/tasks/workitems/random_forest/job-1/task-00028/wd"
declare -x HOME="/mnt/batch/tasks/workitems/random_forest/job-1/task-00028/wd"
declare -x OLDPWD
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/mnt/batch/tasks/shared:/mnt/batch/tasks/workitems/random_forest/job-1/task-00028/wd"
declare -x PWD="/mnt/batch/tasks/workitems/random_forest/job-1/task-00028/wd"
declare -x SHLVL="1"
declare -x USER="_azbatch"
[2018-04-11 20:42:00] Results will not be logged locally.
[2018-04-11 20:42:00] Retrieving tasks...
[2018-04-11 20:42:00] Tasks will be retrieved based on provided task ids.
[2018-04-11 20:42:00] The following tasks were retrieved: [10093].
[2018-04-11 20:42:05] Downloaded task 10093.
[2018-04-11 20:42:05] Prepared pipelines.
[2018-04-11 20:42:05] Started run 1 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:05] Started run 2 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:05] Started run 3 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:05] Started run 4 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:05] Started run 5 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:05] Started run 6 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:05] Started run 7 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:05] Started run 8 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:10] Error in run 1: Run already exists in server. Run id(s): {9027194}
[2018-04-11 20:42:10] Started run 9 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:10] Error in run 2: Run already exists in server. Run id(s): {9027230}
[2018-04-11 20:42:10] Started run 10 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:10] Error in run 3: Run already exists in server. Run id(s): {9027188}
[2018-04-11 20:42:10] Started run 11 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:10] Error in run 4: Run already exists in server. Run id(s): {9027199}
[2018-04-11 20:42:10] Error in run 7: Run already exists in server. Run id(s): {9027218}
[2018-04-11 20:42:10] Started run 12 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:10] Error in run 6: Run already exists in server. Run id(s): {9027203}
[2018-04-11 20:42:10] Error in run 5: Run already exists in server. Run id(s): {9027207}
[2018-04-11 20:42:10] Started run 14 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:10] Error in run 8: Run already exists in server. Run id(s): {9027192}
[2018-04-11 20:42:10] Started run 16 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:10] Started run 13 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:10] Started run 15 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:14] Error in run 9: Run already exists in server. Run id(s): {9027252}
[2018-04-11 20:42:14] Error in run 11: Run already exists in server. Run id(s): {9027242}
[2018-04-11 20:42:14] Started run 17 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:14] Error in run 10: Run already exists in server. Run id(s): {9027240}
[2018-04-11 20:42:14] Started run 19 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:14] Started run 18 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:15] Error in run 13: Run already exists in server. Run id(s): {9027259}
[2018-04-11 20:42:15] Started run 20 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:15] Error in run 12: Run already exists in server. Run id(s): {9027255}
[2018-04-11 20:42:15] Started run 21 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:15] Error in run 15: Run already exists in server. Run id(s): {9027277}
[2018-04-11 20:42:15] Started run 22 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:15] Error in run 14: Run already exists in server. Run id(s): {9027254}
[2018-04-11 20:42:15] Started run 23 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:15] Error in run 16: Run already exists in server. Run id(s): {9027284}
[2018-04-11 20:42:15] Started run 24 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:19] Error in run 19: Run already exists in server. Run id(s): {9027307}
[2018-04-11 20:42:19] Error in run 18: Run already exists in server. Run id(s): {9027295}
[2018-04-11 20:42:19] Error in run 17: Run already exists in server. Run id(s): {9027302}
[2018-04-11 20:42:19] Started run 25 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:19] Started run 27 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:19] Started run 26 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:20] Error in run 20: Run already exists in server. Run id(s): {9027319}
[2018-04-11 20:42:20] Started run 28 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:20] Error in run 23: Run already exists in server. Run id(s): {9027339}
[2018-04-11 20:42:20] Error in run 22: Run already exists in server. Run id(s): {9027317}
[2018-04-11 20:42:20] Started run 29 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:20] Error in run 21: Run already exists in server. Run id(s): {9027325}
[2018-04-11 20:42:20] Error in run 24: Run already exists in server. Run id(s): {9027428}
[2018-04-11 20:42:20] Started run 30 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:20] Started run 31 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:20] Started run 32 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:24] Error in run 26: Run already exists in server. Run id(s): {9027352}
[2018-04-11 20:42:24] Started run 33 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:24] Error in run 25: Run already exists in server. Run id(s): {9027353}
[2018-04-11 20:42:24] Started run 34 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:24] Error in run 27: Run already exists in server. Run id(s): {9027383}
[2018-04-11 20:42:24] Started run 35 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:24] Error in run 30: Run already exists in server. Run id(s): {9027389}
[2018-04-11 20:42:24] Error in run 29: Run already exists in server. Run id(s): {9027382}
[2018-04-11 20:42:24] Error in run 28: Run already exists in server. Run id(s): {9027397}
[2018-04-11 20:42:24] Started run 36 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:24] Error in run 32: Run already exists in server. Run id(s): {9027418}
[2018-04-11 20:42:24] Started run 38 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:24] Error in run 31: Run already exists in server. Run id(s): {9027407}
[2018-04-11 20:42:24] Started run 40 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:24] Started run 37 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:24] Started run 39 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:28] Error in run 33: Run already exists in server. Run id(s): {9027466}
[2018-04-11 20:42:28] Error in run 34: Run already exists in server. Run id(s): {9027430}
[2018-04-11 20:42:28] Error in run 35: Run already exists in server. Run id(s): {9027433}
[2018-04-11 20:42:28] Started run 41 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:28] Started run 42 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:28] Started run 43 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:29] Error in run 38: Run already exists in server. Run id(s): {9027464}
[2018-04-11 20:42:29] Error in run 36: Run already exists in server. Run id(s): {9027454}
[2018-04-11 20:42:29] Error in run 40: Run already exists in server. Run id(s): {9027485}
[2018-04-11 20:42:29] Error in run 39: Run already exists in server. Run id(s): {9027468}
[2018-04-11 20:42:29] Started run 44 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:29] Started run 45 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:29] Error in run 37: Run already exists in server. Run id(s): {9027446}
[2018-04-11 20:42:29] Started run 48 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:29] Started run 46 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:29] Started run 47 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:33] Error in run 42: Run already exists in server. Run id(s): {9027497}
[2018-04-11 20:42:33] Started run 49 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:33] Error in run 43: Run already exists in server. Run id(s): {9027514}
[2018-04-11 20:42:33] Started run 50 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:33] Error in run 41: Run already exists in server. Run id(s): {9027482}
[2018-04-11 20:42:33] Started run 51 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:34] Error in run 44: Run already exists in server. Run id(s): {9027503}
[2018-04-11 20:42:34] Error in run 47: Run already exists in server. Run id(s): {9027525}
[2018-04-11 20:42:34] Started run 52 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:34] Error in run 48: Run already exists in server. Run id(s): {9027538}
[2018-04-11 20:42:34] Started run 53 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:34] Error in run 45: Run already exists in server. Run id(s): {9027513}
[2018-04-11 20:42:34] Started run 54 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:34] Error in run 46: Run already exists in server. Run id(s): {9027517}
[2018-04-11 20:42:34] Started run 55 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:34] Started run 56 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:37] Error in run 49: Run already exists in server. Run id(s): {9027534}
[2018-04-11 20:42:37] Started run 57 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:37] Error in run 50: Run already exists in server. Run id(s): {9027548}
[2018-04-11 20:42:37] Started run 58 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:38] Error in run 51: Run already exists in server. Run id(s): {9027564}
[2018-04-11 20:42:38] Started run 59 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:38] Error in run 54: Run already exists in server. Run id(s): {9027571}
[2018-04-11 20:42:38] Error in run 52: Run already exists in server. Run id(s): {9027586}
[2018-04-11 20:42:38] Error in run 53: Run already exists in server. Run id(s): {9027565}
[2018-04-11 20:42:38] Started run 60 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:38] Error in run 55: Run already exists in server. Run id(s): {9027597}
[2018-04-11 20:42:38] Error in run 56: Run already exists in server. Run id(s): {9027602}
[2018-04-11 20:42:38] Started run 62 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:38] Started run 63 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:38] Started run 61 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:38] Started run 64 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:42] Error in run 57: Run already exists in server. Run id(s): {9027662}
[2018-04-11 20:42:42] Started run 65 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:42] Error in run 59: Run already exists in server. Run id(s): {9027620}
[2018-04-11 20:42:42] Error in run 58: Run already exists in server. Run id(s): {9027610}
[2018-04-11 20:42:42] Started run 66 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:42] Started run 67 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:43] Error in run 61: Run already exists in server. Run id(s): {9027624}
[2018-04-11 20:42:43] Error in run 60: Run already exists in server. Run id(s): {9027616}
[2018-04-11 20:42:43] Error in run 63: Run already exists in server. Run id(s): {9027643}
[2018-04-11 20:42:43] Error in run 62: Run already exists in server. Run id(s): {9027636}
[2018-04-11 20:42:43] Started run 68 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:43] Started run 69 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:43] Error in run 64: Run already exists in server. Run id(s): {9027660}
[2018-04-11 20:42:43] Started run 72 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:43] Started run 70 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:43] Started run 71 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:46] Error in run 65: Run already exists in server. Run id(s): {9027664}
[2018-04-11 20:42:46] Started run 73 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:47] Error in run 66: Run already exists in server. Run id(s): {9027679}
[2018-04-11 20:42:47] Started run 74 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:47] Error in run 67: Run already exists in server. Run id(s): {9027687}
[2018-04-11 20:42:47] Started run 75 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:48] Error in run 71: Run already exists in server. Run id(s): {9027716}
[2018-04-11 20:42:48] Started run 76 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:48] Error in run 69: Run already exists in server. Run id(s): {9027762}
[2018-04-11 20:42:48] Error in run 72: Run already exists in server. Run id(s): {9027734}
[2018-04-11 20:42:48] Error in run 68: Run already exists in server. Run id(s): {9027680}
[2018-04-11 20:42:48] Started run 77 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:48] Error in run 70: Run already exists in server. Run id(s): {9027707}
[2018-04-11 20:42:48] Started run 80 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:48] Started run 78 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:48] Started run 79 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:51] Error in run 73: Run already exists in server. Run id(s): {9027760}
[2018-04-11 20:42:51] Started run 81 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:51] Error in run 74: Run already exists in server. Run id(s): {9027741}
[2018-04-11 20:42:51] Started run 82 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:52] Error in run 75: Run already exists in server. Run id(s): {9027736}
[2018-04-11 20:42:52] Started run 83 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:52] Error in run 79: Run already exists in server. Run id(s): {9027825}
[2018-04-11 20:42:52] Started run 84 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:52] Error in run 77: Run already exists in server. Run id(s): {9027776}
[2018-04-11 20:42:52] Error in run 76: Run already exists in server. Run id(s): {9027842}
[2018-04-11 20:42:52] Started run 85 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:52] Error in run 78: Run already exists in server. Run id(s): {9027781}
[2018-04-11 20:42:52] Started run 87 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:52] Started run 86 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:52] Error in run 80: Run already exists in server. Run id(s): {9027791}
[2018-04-11 20:42:52] Started run 88 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:56] Error in run 81: Run already exists in server. Run id(s): {9027854}
[2018-04-11 20:42:56] Started run 89 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:56] Error in run 82: Run already exists in server. Run id(s): {9027897}
[2018-04-11 20:42:56] Started run 90 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:56] Error in run 83: Run already exists in server. Run id(s): {9027819}
[2018-04-11 20:42:56] Started run 91 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:57] Error in run 84: Run already exists in server. Run id(s): {9027830}
[2018-04-11 20:42:57] Started run 92 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:57] Error in run 85: Run already exists in server. Run id(s): {9027832}
[2018-04-11 20:42:57] Error in run 87: Run already exists in server. Run id(s): {9027869}
[2018-04-11 20:42:57] Started run 93 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:57] Error in run 86: Run already exists in server. Run id(s): {9027836}
[2018-04-11 20:42:57] Error in run 88: Run already exists in server. Run id(s): {9027879}
[2018-04-11 20:42:57] Started run 95 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:57] Started run 96 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:42:57] Started run 94 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:00] Error in run 89: Run already exists in server. Run id(s): {9027881}
[2018-04-11 20:43:00] Started run 97 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:00] Error in run 90: Run already exists in server. Run id(s): {9027884}
[2018-04-11 20:43:00] Started run 98 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:01] Error in run 91: Run already exists in server. Run id(s): {9027898}
[2018-04-11 20:43:01] Started run 99 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:01] Error in run 92: Run already exists in server. Run id(s): {9027901}
[2018-04-11 20:43:01] Started run 100 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:02] Error in run 95: Run already exists in server. Run id(s): {9027969}
[2018-04-11 20:43:02] Error in run 94: Run already exists in server. Run id(s): {9027924}
[2018-04-11 20:43:02] Error in run 96: Run already exists in server. Run id(s): {9027934}
[2018-04-11 20:43:02] Started run 101 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:02] Error in run 93: Run already exists in server. Run id(s): {9027916}
[2018-04-11 20:43:02] Started run 104 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:02] Started run 102 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:02] Started run 103 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:05] Error in run 97: Run already exists in server. Run id(s): {9027937}
[2018-04-11 20:43:05] Started run 105 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:05] Error in run 98: Run already exists in server. Run id(s): {9027990}
[2018-04-11 20:43:05] Started run 106 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:05] Error in run 99: Run already exists in server. Run id(s): {9028024}
[2018-04-11 20:43:05] Started run 107 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:06] Error in run 100: Run already exists in server. Run id(s): {9027953}
[2018-04-11 20:43:06] Started run 108 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:06] Error in run 101: Run already exists in server. Run id(s): {9027976}
[2018-04-11 20:43:06] Started run 109 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:06] Error in run 103: Run already exists in server. Run id(s): {9028002}
[2018-04-11 20:43:06] Started run 110 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:06] Error in run 104: Run already exists in server. Run id(s): {9027997}
[2018-04-11 20:43:06] Started run 111 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:06] Error in run 102: Run already exists in server. Run id(s): {9027980}
[2018-04-11 20:43:06] Started run 112 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:09] Error in run 105: Run already exists in server. Run id(s): {9028020}
[2018-04-11 20:43:09] Started run 113 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:10] Error in run 106: Run already exists in server. Run id(s): {9028032}
[2018-04-11 20:43:10] Started run 114 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:10] Error in run 107: Run already exists in server. Run id(s): {9028031}
[2018-04-11 20:43:10] Started run 115 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:10] Error in run 108: Run already exists in server. Run id(s): {9028039}
[2018-04-11 20:43:10] Started run 116 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:11] Error in run 109: Run already exists in server. Run id(s): {9028057}
[2018-04-11 20:43:11] Started run 117 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:11] Error in run 110: Run already exists in server. Run id(s): {9028053}
[2018-04-11 20:43:11] Error in run 111: Run already exists in server. Run id(s): {9028067}
[2018-04-11 20:43:11] Started run 118 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:11] Error in run 112: Run already exists in server. Run id(s): {9028068}
[2018-04-11 20:43:11] Started run 120 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:11] Started run 119 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:14] Error in run 113: Run already exists in server. Run id(s): {9028087}
[2018-04-11 20:43:14] Started run 121 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:14] Error in run 114: Run already exists in server. Run id(s): {9028084}
[2018-04-11 20:43:14] Started run 122 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:14] Error in run 115: Run already exists in server. Run id(s): {9028090}
[2018-04-11 20:43:14] Started run 123 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:15] Error in run 116: Run already exists in server. Run id(s): {9028095}
[2018-04-11 20:43:15] Started run 124 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:15] Error in run 117: Run already exists in server. Run id(s): {9028106}
[2018-04-11 20:43:15] Started run 125 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:16] Error in run 118: Run already exists in server. Run id(s): {9028113}
[2018-04-11 20:43:16] Started run 126 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:16] Error in run 120: Run already exists in server. Run id(s): {9028148}
[2018-04-11 20:43:16] Started run 127 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:16] Error in run 119: Run already exists in server. Run id(s): {9028147}
[2018-04-11 20:43:16] Started run 128 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:18] Error in run 121: Run already exists in server. Run id(s): {9028143}
[2018-04-11 20:43:18] Started run 129 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:19] Error in run 122: Run already exists in server. Run id(s): {9028154}
[2018-04-11 20:43:19] Started run 130 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:19] Error in run 123: Run already exists in server. Run id(s): {9028166}
[2018-04-11 20:43:19] Started run 131 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:20] Error in run 124: Run already exists in server. Run id(s): {9028199}
[2018-04-11 20:43:20] Started run 132 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:20] Error in run 125: Run already exists in server. Run id(s): {9028179}
[2018-04-11 20:43:20] Started run 133 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:20] Error in run 126: Run already exists in server. Run id(s): {9028184}
[2018-04-11 20:43:20] Started run 134 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:20] Error in run 127: Run already exists in server. Run id(s): {9028196}
[2018-04-11 20:43:20] Started run 135 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:20] Error in run 128: Run already exists in server. Run id(s): {9028207}
[2018-04-11 20:43:20] Started run 136 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:23] Error in run 129: Run already exists in server. Run id(s): {9028213}
[2018-04-11 20:43:23] Started run 137 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:23] Error in run 130: Run already exists in server. Run id(s): {9028239}
[2018-04-11 20:43:23] Started run 138 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:23] Error in run 131: Run already exists in server. Run id(s): {9028235}
[2018-04-11 20:43:23] Started run 139 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:24] Error in run 133: Run already exists in server. Run id(s): {9028241}
[2018-04-11 20:43:24] Error in run 132: Run already exists in server. Run id(s): {9028232}
[2018-04-11 20:43:24] Started run 140 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:24] Started run 141 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:25] Error in run 134: Run already exists in server. Run id(s): {9028254}
[2018-04-11 20:43:25] Started run 142 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:25] Error in run 135: Run already exists in server. Run id(s): {9028240}
[2018-04-11 20:43:25] Started run 143 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:25] Error in run 136: Run already exists in server. Run id(s): {9028248}
[2018-04-11 20:43:25] Started run 144 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:27] Error in run 137: Run already exists in server. Run id(s): {9028285}
[2018-04-11 20:43:27] Started run 145 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:28] Error in run 138: Run already exists in server. Run id(s): {9028314}
[2018-04-11 20:43:28] Started run 146 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:28] Error in run 139: Run already exists in server. Run id(s): {9028287}
[2018-04-11 20:43:28] Started run 147 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:29] Error in run 141: Run already exists in server. Run id(s): {9028295}
[2018-04-11 20:43:29] Error in run 140: Run already exists in server. Run id(s): {9028300}
[2018-04-11 20:43:29] Started run 148 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:29] Started run 149 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:29] Error in run 142: Run already exists in server. Run id(s): {9028291}
[2018-04-11 20:43:29] Started run 150 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:29] Error in run 143: Run already exists in server. Run id(s): {9028337}
[2018-04-11 20:43:29] Started run 151 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:30] Error in run 144: Run already exists in server. Run id(s): {9028308}
[2018-04-11 20:43:30] Started run 152 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:32] Error in run 145: Run already exists in server. Run id(s): {9028342}
[2018-04-11 20:43:32] Started run 153 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:32] Error in run 146: Run already exists in server. Run id(s): {9028334}
[2018-04-11 20:43:32] Started run 154 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:33] Error in run 147: Run already exists in server. Run id(s): {9028339}
[2018-04-11 20:43:33] Started run 155 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:34] Error in run 149: Run already exists in server. Run id(s): {9028359}
[2018-04-11 20:43:34] Started run 156 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:34] Error in run 150: Run already exists in server. Run id(s): {9028385}
[2018-04-11 20:43:34] Started run 157 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:34] Error in run 148: Run already exists in server. Run id(s): {9028357}
[2018-04-11 20:43:34] Started run 158 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:34] Error in run 151: Run already exists in server. Run id(s): {9028370}
[2018-04-11 20:43:34] Started run 159 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:35] Error in run 152: Run already exists in server. Run id(s): {9028390}
[2018-04-11 20:43:35] Started run 160 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:37] Error in run 153: Run already exists in server. Run id(s): {9028396}
[2018-04-11 20:43:37] Started run 161 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:37] Error in run 154: Run already exists in server. Run id(s): {9028397}
[2018-04-11 20:43:37] Started run 162 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:38] Error in run 155: Run already exists in server. Run id(s): {9028427}
[2018-04-11 20:43:38] Started run 163 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:38] Error in run 157: Run already exists in server. Run id(s): {9028411}
[2018-04-11 20:43:38] Started run 164 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:38] Error in run 158: Run already exists in server. Run id(s): {9028421}
[2018-04-11 20:43:38] Error in run 156: Run already exists in server. Run id(s): {9028407}
[2018-04-11 20:43:38] Started run 165 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:38] Error in run 159: Run already exists in server. Run id(s): {9028441}
[2018-04-11 20:43:38] Started run 167 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:38] Started run 166 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:39] Error in run 160: Run already exists in server. Run id(s): {9028451}
[2018-04-11 20:43:39] Started run 168 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:41] Error in run 161: Run already exists in server. Run id(s): {9028458}
[2018-04-11 20:43:41] Started run 169 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:41] Error in run 162: Run already exists in server. Run id(s): {9028450}
[2018-04-11 20:43:41] Started run 170 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:42] Error in run 163: Run already exists in server. Run id(s): {9028456}
[2018-04-11 20:43:42] Started run 171 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:43] Error in run 165: Run already exists in server. Run id(s): {9028479}
[2018-04-11 20:43:43] Error in run 166: Run already exists in server. Run id(s): {9028483}
[2018-04-11 20:43:43] Error in run 164: Run already exists in server. Run id(s): {9028476}
[2018-04-11 20:43:43] Started run 172 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:43] Error in run 167: Run already exists in server. Run id(s): {9028510}
[2018-04-11 20:43:43] Started run 173 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:43] Started run 175 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:43] Started run 174 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:44] Error in run 168: Run already exists in server. Run id(s): {9028509}
[2018-04-11 20:43:44] Started run 176 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:46] Error in run 169: Run already exists in server. Run id(s): {9028503}
[2018-04-11 20:43:46] Started run 177 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:46] Error in run 170: Run already exists in server. Run id(s): {9028507}
[2018-04-11 20:43:46] Started run 178 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:47] Error in run 171: Run already exists in server. Run id(s): {9028506}
[2018-04-11 20:43:47] Started run 179 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:48] Error in run 173: Run already exists in server. Run id(s): {9028534}
[2018-04-11 20:43:48] Error in run 174: Run already exists in server. Run id(s): {9028521}
[2018-04-11 20:43:48] Started run 180 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:48] Error in run 175: Run already exists in server. Run id(s): {9028558}
[2018-04-11 20:43:48] Started run 182 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:48] Error in run 172: Run already exists in server. Run id(s): {9028516}
[2018-04-11 20:43:48] Started run 183 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:48] Started run 181 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:48] Error in run 176: Run already exists in server. Run id(s): {9028557}
[2018-04-11 20:43:48] Started run 184 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:50] Error in run 177: Run already exists in server. Run id(s): {9028561}
[2018-04-11 20:43:50] Started run 185 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:51] Error in run 178: Run already exists in server. Run id(s): {9028563}
[2018-04-11 20:43:51] Started run 186 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:52] Error in run 179: Run already exists in server. Run id(s): {9028559}
[2018-04-11 20:43:52] Started run 187 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:52] Error in run 182: Run already exists in server. Run id(s): {9028599}
[2018-04-11 20:43:52] Error in run 181: Run already exists in server. Run id(s): {9028590}
[2018-04-11 20:43:52] Started run 188 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:52] Error in run 183: Run already exists in server. Run id(s): {9028657}
[2018-04-11 20:43:52] Started run 189 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:52] Error in run 180: Run already exists in server. Run id(s): {9028575}
[2018-04-11 20:43:52] Started run 191 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:52] Started run 190 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:53] Error in run 184: Run already exists in server. Run id(s): {9028677}
[2018-04-11 20:43:53] Started run 192 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:55] Error in run 185: Run already exists in server. Run id(s): {9028611}
[2018-04-11 20:43:55] Started run 193 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:55] Error in run 186: Run already exists in server. Run id(s): {9028613}
[2018-04-11 20:43:55] Started run 194 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:56] Error in run 187: Run already exists in server. Run id(s): {9028630}
[2018-04-11 20:43:56] Started run 195 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:57] Error in run 191: Run already exists in server. Run id(s): {9028666}
[2018-04-11 20:43:57] Error in run 190: Run already exists in server. Run id(s): {9028659}
[2018-04-11 20:43:57] Started run 196 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:57] Started run 197 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:57] Error in run 188: Run already exists in server. Run id(s): {9028639}
[2018-04-11 20:43:57] Started run 198 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:57] Error in run 189: Run already exists in server. Run id(s): {9028643}
[2018-04-11 20:43:57] Started run 199 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:58] Error in run 192: Run already exists in server. Run id(s): {9028794}
[2018-04-11 20:43:58] Started run 200 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:43:59] Error in run 193: Run already exists in server. Run id(s): {9028687}
[2018-04-11 20:43:59] Started run 201 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:01] Error in run 194: Run already exists in server. Run id(s): {9028698}
[2018-04-11 20:44:01] Started run 202 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:02] Error in run 195: Run already exists in server. Run id(s): {9028694}
[2018-04-11 20:44:02] Started run 203 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:03] Error in run 199: Run already exists in server. Run id(s): {9028748}
[2018-04-11 20:44:03] Error in run 198: Run already exists in server. Run id(s): {9028725}
[2018-04-11 20:44:03] Started run 204 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:03] Error in run 197: Run already exists in server. Run id(s): {9028719}
[2018-04-11 20:44:03] Started run 206 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:03] Error in run 196: Run already exists in server. Run id(s): {9028730}
[2018-04-11 20:44:03] Started run 207 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:03] Started run 205 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:04] Error in run 200: Run already exists in server. Run id(s): {9028752}
[2018-04-11 20:44:04] Started run 208 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:05] Error in run 201: Run already exists in server. Run id(s): {9028761}
[2018-04-11 20:44:05] Started run 209 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:06] Error in run 202: Run already exists in server. Run id(s): {9028764}
[2018-04-11 20:44:06] Started run 210 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:07] Error in run 203: Run already exists in server. Run id(s): {9028834}
[2018-04-11 20:44:07] Started run 211 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:07] Error in run 206: Run already exists in server. Run id(s): {9028795}
[2018-04-11 20:44:07] Started run 212 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:07] Error in run 204: Run already exists in server. Run id(s): {9028776}
[2018-04-11 20:44:07] Started run 213 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:07] Error in run 207: Run already exists in server. Run id(s): {9028802}
[2018-04-11 20:44:07] Started run 214 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:07] Error in run 205: Run already exists in server. Run id(s): {9028854}
[2018-04-11 20:44:07] Started run 215 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:08] Error in run 208: Run already exists in server. Run id(s): {9028801}
[2018-04-11 20:44:08] Started run 216 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:10] Error in run 209: Run already exists in server. Run id(s): {9028811}
[2018-04-11 20:44:10] Started run 217 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:10] Error in run 210: Run already exists in server. Run id(s): {9028843}
[2018-04-11 20:44:10] Started run 218 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:11] Error in run 211: Run already exists in server. Run id(s): {9028848}
[2018-04-11 20:44:11] Started run 219 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:12] Error in run 213: Run already exists in server. Run id(s): {9028871}
[2018-04-11 20:44:12] Started run 220 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:12] Error in run 212: Run already exists in server. Run id(s): {9028862}
[2018-04-11 20:44:12] Started run 221 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:12] Error in run 214: Run already exists in server. Run id(s): {9028921}
[2018-04-11 20:44:12] Error in run 215: Run already exists in server. Run id(s): {9028870}
[2018-04-11 20:44:12] Started run 222 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:12] Started run 223 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:13] Error in run 216: Run already exists in server. Run id(s): {9028896}
[2018-04-11 20:44:13] Started run 224 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:14] Error in run 217: Run already exists in server. Run id(s): {9028924}
[2018-04-11 20:44:14] Started run 225 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:15] Error in run 218: Run already exists in server. Run id(s): {9028910}
[2018-04-11 20:44:15] Started run 226 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:16] Error in run 219: Run already exists in server. Run id(s): {9028906}
[2018-04-11 20:44:16] Started run 227 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:17] Error in run 223: Run already exists in server. Run id(s): {9028947}
[2018-04-11 20:44:17] Error in run 221: Run already exists in server. Run id(s): {9028928}
[2018-04-11 20:44:17] Error in run 222: Run already exists in server. Run id(s): {9028929}
[2018-04-11 20:44:17] Started run 228 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:17] Started run 229 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:17] Started run 230 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:17] Error in run 220: Run already exists in server. Run id(s): {9028925}
[2018-04-11 20:44:17] Started run 231 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:17] Error in run 224: Run already exists in server. Run id(s): {9028960}
[2018-04-11 20:44:17] Started run 232 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:19] Error in run 225: Run already exists in server. Run id(s): {9029090}
[2018-04-11 20:44:19] Started run 233 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:20] Error in run 226: Run already exists in server. Run id(s): {9028998}
[2018-04-11 20:44:20] Started run 234 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:20] Error in run 227: Run already exists in server. Run id(s): {9028972}
[2018-04-11 20:44:20] Started run 235 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:21] Error in run 228: Run already exists in server. Run id(s): {9029070}
[2018-04-11 20:44:21] Started run 236 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:21] Error in run 231: Run already exists in server. Run id(s): {9028992}
[2018-04-11 20:44:21] Error in run 230: Run already exists in server. Run id(s): {9028983}
[2018-04-11 20:44:21] Started run 237 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:21] Error in run 229: Run already exists in server. Run id(s): {9028974}
[2018-04-11 20:44:21] Started run 238 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:21] Started run 239 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:22] Error in run 232: Run already exists in server. Run id(s): {9029009}
[2018-04-11 20:44:22] Started run 240 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:24] Error in run 233: Run already exists in server. Run id(s): {9029025}
[2018-04-11 20:44:24] Started run 241 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:24] Error in run 234: Run already exists in server. Run id(s): {9029030}
[2018-04-11 20:44:24] Started run 242 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:25] Error in run 235: Run already exists in server. Run id(s): {9029036}
[2018-04-11 20:44:25] Started run 243 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:26] Error in run 236: Run already exists in server. Run id(s): {9029060}
[2018-04-11 20:44:26] Started run 244 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:26] Error in run 239: Run already exists in server. Run id(s): {9029088}
[2018-04-11 20:44:26] Error in run 238: Run already exists in server. Run id(s): {9029068}
[2018-04-11 20:44:26] Started run 245 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:26] Error in run 237: Run already exists in server. Run id(s): {9029063}
[2018-04-11 20:44:26] Started run 247 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:26] Started run 246 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:26] Error in run 240: Run already exists in server. Run id(s): {9029152}
[2018-04-11 20:44:26] Started run 248 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:28] Error in run 241: Run already exists in server. Run id(s): {9029113}
[2018-04-11 20:44:28] Started run 249 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:29] Error in run 242: Run already exists in server. Run id(s): {9029115}
[2018-04-11 20:44:29] Started run 250 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:29] Error in run 243: Run already exists in server. Run id(s): {9029126}
[2018-04-11 20:44:29] Started run 251 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:30] Error in run 244: Run already exists in server. Run id(s): {9029128}
[2018-04-11 20:44:30] Started run 252 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:30] Error in run 246: Run already exists in server. Run id(s): {9029154}
[2018-04-11 20:44:30] Started run 253 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:31] Error in run 245: Run already exists in server. Run id(s): {9029140}
[2018-04-11 20:44:31] Started run 254 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:31] Error in run 247: Run already exists in server. Run id(s): {9029161}
[2018-04-11 20:44:31] Started run 255 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:31] Error in run 248: Run already exists in server. Run id(s): {9029183}
[2018-04-11 20:44:31] Started run 256 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:33] Error in run 249: Run already exists in server. Run id(s): {9029269}
[2018-04-11 20:44:33] Started run 257 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:33] Error in run 250: Run already exists in server. Run id(s): {9029189}
[2018-04-11 20:44:33] Started run 258 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:34] Error in run 251: Run already exists in server. Run id(s): {9029184}
[2018-04-11 20:44:34] Started run 259 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:35] Error in run 252: Run already exists in server. Run id(s): {9029209}
[2018-04-11 20:44:35] Started run 260 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:35] Error in run 253: Run already exists in server. Run id(s): {9029355}
[2018-04-11 20:44:35] Started run 261 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:35] Error in run 254: Run already exists in server. Run id(s): {9029213}
[2018-04-11 20:44:35] Started run 262 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:35] Error in run 255: Run already exists in server. Run id(s): {9029264}
[2018-04-11 20:44:35] Started run 263 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:35] Error in run 256: Run already exists in server. Run id(s): {9029247}
[2018-04-11 20:44:35] Started run 264 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:38] Error in run 257: Run already exists in server. Run id(s): {9029239}
[2018-04-11 20:44:38] Started run 265 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:38] Error in run 258: Run already exists in server. Run id(s): {9029251}
[2018-04-11 20:44:38] Started run 266 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:38] Error in run 259: Run already exists in server. Run id(s): {9029307}
[2018-04-11 20:44:38] Started run 267 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:39] Error in run 260: Run already exists in server. Run id(s): {9029278}
[2018-04-11 20:44:39] Started run 268 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:39] Error in run 261: Run already exists in server. Run id(s): {9029299}
[2018-04-11 20:44:39] Started run 269 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:40] Error in run 262: Run already exists in server. Run id(s): {9029310}
[2018-04-11 20:44:40] Started run 270 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:40] Error in run 263: Run already exists in server. Run id(s): {9029311}
[2018-04-11 20:44:40] Started run 271 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:40] Error in run 264: Run already exists in server. Run id(s): {9029320}
[2018-04-11 20:44:40] Started run 272 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:42] Error in run 265: Run already exists in server. Run id(s): {9029329}
[2018-04-11 20:44:42] Started run 273 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:43] Error in run 266: Run already exists in server. Run id(s): {9029330}
[2018-04-11 20:44:43] Started run 274 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:43] Error in run 267: Run already exists in server. Run id(s): {9029397}
[2018-04-11 20:44:43] Started run 275 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:44] Error in run 268: Run already exists in server. Run id(s): {9029374}
[2018-04-11 20:44:44] Started run 276 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:44] Error in run 269: Run already exists in server. Run id(s): {9029387}
[2018-04-11 20:44:44] Started run 277 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:44] Error in run 270: Run already exists in server. Run id(s): {9029369}
[2018-04-11 20:44:44] Started run 278 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:44] Error in run 271: Run already exists in server. Run id(s): {9029383}
[2018-04-11 20:44:44] Started run 279 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:45] Error in run 272: Run already exists in server. Run id(s): {9029386}
[2018-04-11 20:44:45] Started run 280 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:47] Error in run 273: Run already exists in server. Run id(s): {9029399}
[2018-04-11 20:44:47] Started run 281 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:47] Error in run 274: Run already exists in server. Run id(s): {9029418}
[2018-04-11 20:44:47] Started run 282 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:48] Error in run 275: Run already exists in server. Run id(s): {9029435}
[2018-04-11 20:44:48] Started run 283 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:48] Error in run 276: Run already exists in server. Run id(s): {9029433}
[2018-04-11 20:44:48] Started run 284 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:48] Error in run 277: Run already exists in server. Run id(s): {9029448}
[2018-04-11 20:44:48] Started run 285 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:49] Error in run 278: Run already exists in server. Run id(s): {9029444}
[2018-04-11 20:44:49] Started run 286 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:49] Error in run 279: Run already exists in server. Run id(s): {9029525}
[2018-04-11 20:44:49] Started run 287 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:49] Error in run 280: Run already exists in server. Run id(s): {9029535}
[2018-04-11 20:44:49] Started run 288 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:51] Error in run 281: Run already exists in server. Run id(s): {9029457}
[2018-04-11 20:44:51] Started run 289 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:52] Error in run 282: Run already exists in server. Run id(s): {9029474}
[2018-04-11 20:44:52] Started run 290 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:52] Error in run 283: Run already exists in server. Run id(s): {9029481}
[2018-04-11 20:44:52] Started run 291 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:53] Error in run 284: Run already exists in server. Run id(s): {9029489}
[2018-04-11 20:44:53] Error in run 287: Run already exists in server. Run id(s): {9029521}
[2018-04-11 20:44:53] Started run 292 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:53] Error in run 286: Run already exists in server. Run id(s): {9029508}
[2018-04-11 20:44:53] Started run 294 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:53] Error in run 285: Run already exists in server. Run id(s): {9029487}
[2018-04-11 20:44:53] Started run 295 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:53] Started run 293 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:54] Error in run 288: Run already exists in server. Run id(s): {9029527}
[2018-04-11 20:44:54] Started run 296 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:56] Error in run 289: Run already exists in server. Run id(s): {9029563}
[2018-04-11 20:44:56] Started run 297 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:56] Error in run 290: Run already exists in server. Run id(s): {9029558}
[2018-04-11 20:44:56] Started run 298 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:57] Error in run 291: Run already exists in server. Run id(s): {9029553}
[2018-04-11 20:44:57] Started run 299 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:58] Error in run 292: Run already exists in server. Run id(s): {9029566}
[2018-04-11 20:44:58] Started run 300 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:58] Error in run 293: Run already exists in server. Run id(s): {9029578}
[2018-04-11 20:44:58] Error in run 295: Run already exists in server. Run id(s): {9029580}
[2018-04-11 20:44:58] Error in run 294: Run already exists in server. Run id(s): {9029583}
[2018-04-11 20:44:58] Started run 301 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:58] Started run 302 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:58] Started run 303 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:44:59] Error in run 296: Run already exists in server. Run id(s): {9029598}
[2018-04-11 20:44:59] Started run 304 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:00] Error in run 297: Run already exists in server. Run id(s): {9029618}
[2018-04-11 20:45:00] Started run 305 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:01] Error in run 298: Run already exists in server. Run id(s): {9029607}
[2018-04-11 20:45:01] Started run 306 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:02] Error in run 299: Run already exists in server. Run id(s): {9029621}
[2018-04-11 20:45:02] Started run 307 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:02] Error in run 300: Run already exists in server. Run id(s): {9029614}
[2018-04-11 20:45:02] Started run 308 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:03] Error in run 303: Run already exists in server. Run id(s): {9029636}
[2018-04-11 20:45:03] Error in run 302: Run already exists in server. Run id(s): {9029685}
[2018-04-11 20:45:03] Started run 309 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:03] Error in run 301: Run already exists in server. Run id(s): {9029633}
[2018-04-11 20:45:03] Started run 310 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:03] Started run 311 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:03] Error in run 304: Run already exists in server. Run id(s): {9029729}
[2018-04-11 20:45:03] Started run 312 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:05] Error in run 305: Run already exists in server. Run id(s): {9029777}
[2018-04-11 20:45:05] Started run 313 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:05] Error in run 306: Run already exists in server. Run id(s): {9029674}
[2018-04-11 20:45:05] Started run 314 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:06] Error in run 307: Run already exists in server. Run id(s): {9029691}
[2018-04-11 20:45:06] Started run 315 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:07] Error in run 308: Run already exists in server. Run id(s): {9029672}
[2018-04-11 20:45:07] Started run 316 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:07] Error in run 309: Run already exists in server. Run id(s): {9029687}
[2018-04-11 20:45:07] Started run 317 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:07] Error in run 310: Run already exists in server. Run id(s): {9029708}
[2018-04-11 20:45:07] Started run 318 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:07] Error in run 311: Run already exists in server. Run id(s): {9029769}
[2018-04-11 20:45:07] Started run 319 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:08] Error in run 312: Run already exists in server. Run id(s): {9029730}
[2018-04-11 20:45:08] Started run 320 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:10] Error in run 313: Run already exists in server. Run id(s): {9029755}
[2018-04-11 20:45:10] Started run 321 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:10] Error in run 314: Run already exists in server. Run id(s): {9029733}
[2018-04-11 20:45:10] Started run 322 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:11] Error in run 315: Run already exists in server. Run id(s): {9029728}
[2018-04-11 20:45:11] Started run 323 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:11] Error in run 316: Run already exists in server. Run id(s): {9029772}
[2018-04-11 20:45:11] Started run 324 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:12] Error in run 317: Run already exists in server. Run id(s): {9029781}
[2018-04-11 20:45:12] Started run 325 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:12] Error in run 319: Run already exists in server. Run id(s): {9029787}
[2018-04-11 20:45:12] Started run 326 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:12] Error in run 318: Run already exists in server. Run id(s): {9029788}
[2018-04-11 20:45:12] Started run 327 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:12] Error in run 320: Run already exists in server. Run id(s): {9029887}
[2018-04-11 20:45:12] Started run 328 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:14] Error in run 321: Run already exists in server. Run id(s): {9029809}
[2018-04-11 20:45:14] Started run 329 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:14] Error in run 322: Run already exists in server. Run id(s): {9029828}
[2018-04-11 20:45:14] Started run 330 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:15] Error in run 323: Run already exists in server. Run id(s): {9029834}
[2018-04-11 20:45:15] Started run 331 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:16] Error in run 324: Run already exists in server. Run id(s): {9029847}
[2018-04-11 20:45:16] Started run 332 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:16] Error in run 325: Run already exists in server. Run id(s): {9029832}
[2018-04-11 20:45:16] Started run 333 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:16] Error in run 326: Run already exists in server. Run id(s): {9029837}
[2018-04-11 20:45:16] Started run 334 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:16] Error in run 327: Run already exists in server. Run id(s): {9029844}
[2018-04-11 20:45:16] Started run 335 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:17] Error in run 328: Run already exists in server. Run id(s): {9029859}
[2018-04-11 20:45:17] Started run 336 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:19] Error in run 329: Run already exists in server. Run id(s): {9029880}
[2018-04-11 20:45:19] Started run 337 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:19] Error in run 330: Run already exists in server. Run id(s): {9029903}
[2018-04-11 20:45:19] Started run 338 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:20] Error in run 331: Run already exists in server. Run id(s): {9029902}
[2018-04-11 20:45:20] Started run 339 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:20] Error in run 332: Run already exists in server. Run id(s): {9029885}
[2018-04-11 20:45:20] Started run 340 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:21] Error in run 333: Run already exists in server. Run id(s): {9029901}
[2018-04-11 20:45:21] Started run 341 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:21] Error in run 334: Run already exists in server. Run id(s): {9029909}
[2018-04-11 20:45:21] Started run 342 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:21] Error in run 336: Run already exists in server. Run id(s): {9029934}
[2018-04-11 20:45:21] Error in run 335: Run already exists in server. Run id(s): {9029910}
[2018-04-11 20:45:21] Started run 343 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:21] Started run 344 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:23] Error in run 337: Run already exists in server. Run id(s): {9029947}
[2018-04-11 20:45:23] Started run 345 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:24] Error in run 338: Run already exists in server. Run id(s): {9029951}
[2018-04-11 20:45:24] Started run 346 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:24] Error in run 339: Run already exists in server. Run id(s): {9029965}
[2018-04-11 20:45:24] Started run 347 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:25] Error in run 340: Run already exists in server. Run id(s): {9029966}
[2018-04-11 20:45:25] Started run 348 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:25] Error in run 341: Run already exists in server. Run id(s): {9029960}
[2018-04-11 20:45:25] Started run 349 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:26] Error in run 342: Run already exists in server. Run id(s): {9029964}
[2018-04-11 20:45:26] Started run 350 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:26] Error in run 343: Run already exists in server. Run id(s): {9030040}
[2018-04-11 20:45:26] Started run 351 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:26] Error in run 344: Run already exists in server. Run id(s): {9029992}
[2018-04-11 20:45:26] Started run 352 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:28] Error in run 345: Run already exists in server. Run id(s): {9030002}
[2018-04-11 20:45:28] Started run 353 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:28] Error in run 346: Run already exists in server. Run id(s): {9030011}
[2018-04-11 20:45:28] Started run 354 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:29] Error in run 347: Run already exists in server. Run id(s): {9030016}
[2018-04-11 20:45:29] Started run 355 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:30] Error in run 349: Run already exists in server. Run id(s): {9030013}
[2018-04-11 20:45:30] Error in run 348: Run already exists in server. Run id(s): {9030009}
[2018-04-11 20:45:30] Started run 356 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:30] Started run 357 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:30] Error in run 350: Run already exists in server. Run id(s): {9030017}
[2018-04-11 20:45:30] Started run 358 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:30] Error in run 352: Run already exists in server. Run id(s): {9030053}
[2018-04-11 20:45:30] Started run 359 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:31] Error in run 351: Run already exists in server. Run id(s): {9030140, 9030206}
[2018-04-11 20:45:31] Started run 360 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:33] Error in run 353: Run already exists in server. Run id(s): {9030074}
[2018-04-11 20:45:33] Started run 361 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:33] Error in run 354: Run already exists in server. Run id(s): {9030157}
[2018-04-11 20:45:33] Started run 362 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:34] Error in run 355: Run already exists in server. Run id(s): {9030068}
[2018-04-11 20:45:34] Started run 363 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:34] Error in run 357: Run already exists in server. Run id(s): {9030060}
[2018-04-11 20:45:34] Started run 364 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:34] Error in run 356: Run already exists in server. Run id(s): {9030059}
[2018-04-11 20:45:34] Started run 365 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:35] Error in run 358: Run already exists in server. Run id(s): {9030089}
[2018-04-11 20:45:35] Started run 366 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:35] Error in run 359: Run already exists in server. Run id(s): {9030116}
[2018-04-11 20:45:35] Started run 367 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:35] Error in run 360: Run already exists in server. Run id(s): {9030120}
[2018-04-11 20:45:35] Started run 368 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:37] Error in run 361: Run already exists in server. Run id(s): {9030126}
[2018-04-11 20:45:37] Started run 369 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:37] Error in run 362: Run already exists in server. Run id(s): {9030200}
[2018-04-11 20:45:37] Started run 370 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:38] Error in run 363: Run already exists in server. Run id(s): {9030142}
[2018-04-11 20:45:38] Started run 371 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:39] Error in run 364: Run already exists in server. Run id(s): {9030149}
[2018-04-11 20:45:39] Started run 372 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:39] Error in run 365: Run already exists in server. Run id(s): {9030180}
[2018-04-11 20:45:39] Started run 373 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:39] Error in run 366: Run already exists in server. Run id(s): {9030175}
[2018-04-11 20:45:39] Started run 374 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:39] Error in run 367: Run already exists in server. Run id(s): {9030185}
[2018-04-11 20:45:39] Started run 375 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:40] Error in run 368: Run already exists in server. Run id(s): {9030194}
[2018-04-11 20:45:40] Started run 376 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:42] Error in run 369: Run already exists in server. Run id(s): {9030218}
[2018-04-11 20:45:42] Started run 377 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:42] Error in run 370: Run already exists in server. Run id(s): {9030212}
[2018-04-11 20:45:42] Started run 378 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:43] Error in run 371: Run already exists in server. Run id(s): {9030250}
[2018-04-11 20:45:43] Started run 379 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:43] Error in run 372: Run already exists in server. Run id(s): {9030234}
[2018-04-11 20:45:43] Started run 380 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:44] Error in run 373: Run already exists in server. Run id(s): {9030239}
[2018-04-11 20:45:44] Started run 381 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:44] Error in run 374: Run already exists in server. Run id(s): {9030261}
[2018-04-11 20:45:44] Started run 382 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:44] Error in run 375: Run already exists in server. Run id(s): {9030247}
[2018-04-11 20:45:44] Started run 383 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:44] Error in run 376: Run already exists in server. Run id(s): {9030257}
[2018-04-11 20:45:44] Started run 384 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:46] Error in run 377: Run already exists in server. Run id(s): {9030272}
[2018-04-11 20:45:46] Started run 385 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:46] Error in run 378: Run already exists in server. Run id(s): {9030274}
[2018-04-11 20:45:46] Started run 386 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:47] Error in run 379: Run already exists in server. Run id(s): {9030292}
[2018-04-11 20:45:47] Started run 387 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:48] Error in run 380: Run already exists in server. Run id(s): {9030308}
[2018-04-11 20:45:48] Started run 388 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:48] Error in run 381: Run already exists in server. Run id(s): {9030306}
[2018-04-11 20:45:48] Started run 389 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:48] Error in run 382: Run already exists in server. Run id(s): {9030309}
[2018-04-11 20:45:48] Started run 390 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:49] Error in run 383: Run already exists in server. Run id(s): {9030314}
[2018-04-11 20:45:49] Started run 391 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:49] Error in run 384: Run already exists in server. Run id(s): {9030333}
[2018-04-11 20:45:49] Started run 392 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:51] Error in run 385: Run already exists in server. Run id(s): {9030321}
[2018-04-11 20:45:51] Started run 393 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:51] Error in run 386: Run already exists in server. Run id(s): {9030377}
[2018-04-11 20:45:51] Started run 394 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:52] Error in run 387: Run already exists in server. Run id(s): {9030363}
[2018-04-11 20:45:52] Started run 395 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:52] Error in run 388: Run already exists in server. Run id(s): {9030346}
[2018-04-11 20:45:52] Started run 396 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:53] Error in run 389: Run already exists in server. Run id(s): {9030349}
[2018-04-11 20:45:53] Started run 397 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:53] Error in run 390: Run already exists in server. Run id(s): {9030351}
[2018-04-11 20:45:53] Started run 398 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:53] Error in run 391: Run already exists in server. Run id(s): {9030367}
[2018-04-11 20:45:53] Error in run 392: Run already exists in server. Run id(s): {9030368}
[2018-04-11 20:45:53] Started run 399 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:53] Started run 400 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:55] Error in run 393: Run already exists in server. Run id(s): {9030384}
[2018-04-11 20:45:55] Started run 401 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:56] Error in run 394: Run already exists in server. Run id(s): {9030400}
[2018-04-11 20:45:56] Started run 402 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:56] Error in run 395: Run already exists in server. Run id(s): {9030413}
[2018-04-11 20:45:56] Started run 403 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:57] Error in run 396: Run already exists in server. Run id(s): {9030404}
[2018-04-11 20:45:57] Started run 404 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:57] Error in run 397: Run already exists in server. Run id(s): {9030423}
[2018-04-11 20:45:57] Started run 405 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:58] Error in run 398: Run already exists in server. Run id(s): {9030430}
[2018-04-11 20:45:58] Started run 406 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:58] Error in run 400: Run already exists in server. Run id(s): {9030472}
[2018-04-11 20:45:58] Started run 407 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:45:58] Error in run 399: Run already exists in server. Run id(s): {9030429}
[2018-04-11 20:45:58] Started run 408 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:00] Error in run 401: Run already exists in server. Run id(s): {9030441}
[2018-04-11 20:46:00] Started run 409 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:00] Error in run 402: Run already exists in server. Run id(s): {9030450}
[2018-04-11 20:46:00] Started run 410 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:01] Error in run 403: Run already exists in server. Run id(s): {9030457}
[2018-04-11 20:46:01] Started run 411 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:02] Error in run 404: Run already exists in server. Run id(s): {9030476}
[2018-04-11 20:46:02] Started run 412 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:02] Error in run 405: Run already exists in server. Run id(s): {9030486}
[2018-04-11 20:46:02] Started run 413 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:02] Error in run 406: Run already exists in server. Run id(s): {9030481}
[2018-04-11 20:46:02] Started run 414 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:03] Error in run 408: Run already exists in server. Run id(s): {9030491}
[2018-04-11 20:46:03] Started run 415 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:03] Error in run 407: Run already exists in server. Run id(s): {9030485}
[2018-04-11 20:46:03] Started run 416 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:04] Error in run 409: Run already exists in server. Run id(s): {9030496}
[2018-04-11 20:46:04] Started run 417 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:05] Error in run 410: Run already exists in server. Run id(s): {9030517}
[2018-04-11 20:46:05] Started run 418 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:06] Error in run 411: Run already exists in server. Run id(s): {9030539}
[2018-04-11 20:46:06] Started run 419 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:06] Error in run 413: Run already exists in server. Run id(s): {9030558}
[2018-04-11 20:46:06] Started run 420 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:06] Error in run 412: Run already exists in server. Run id(s): {9030528}
[2018-04-11 20:46:06] Started run 421 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:07] Error in run 414: Run already exists in server. Run id(s): {9030540}
[2018-04-11 20:46:07] Started run 422 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:07] Error in run 416: Run already exists in server. Run id(s): {9030548}
[2018-04-11 20:46:07] Started run 423 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:07] Error in run 415: Run already exists in server. Run id(s): {9030546}
[2018-04-11 20:46:07] Started run 424 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:09] Error in run 417: Run already exists in server. Run id(s): {9030570}
[2018-04-11 20:46:09] Started run 425 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:10] Error in run 418: Run already exists in server. Run id(s): {9030572}
[2018-04-11 20:46:10] Started run 426 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:10] Error in run 419: Run already exists in server. Run id(s): {9030640}
[2018-04-11 20:46:10] Started run 427 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:11] Error in run 420: Run already exists in server. Run id(s): {9030585}
[2018-04-11 20:46:11] Started run 428 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:11] Error in run 422: Run already exists in server. Run id(s): {9030606}
[2018-04-11 20:46:11] Error in run 421: Run already exists in server. Run id(s): {9030590}
[2018-04-11 20:46:11] Started run 429 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:11] Started run 430 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:12] Error in run 424: Run already exists in server. Run id(s): {9030604}
[2018-04-11 20:46:12] Started run 431 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:12] Error in run 423: Run already exists in server. Run id(s): {9030594}
[2018-04-11 20:46:12] Started run 432 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:14] Error in run 425: Run already exists in server. Run id(s): {9030619}
[2018-04-11 20:46:14] Started run 433 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:14] Error in run 426: Run already exists in server. Run id(s): {9030621}
[2018-04-11 20:46:14] Started run 434 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:15] Error in run 427: Run already exists in server. Run id(s): {9030638}
[2018-04-11 20:46:15] Started run 435 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:16] Error in run 428: Run already exists in server. Run id(s): {9030713}
[2018-04-11 20:46:16] Started run 436 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:16] Error in run 430: Run already exists in server. Run id(s): {9030664}
[2018-04-11 20:46:16] Error in run 429: Run already exists in server. Run id(s): {9030646}
[2018-04-11 20:46:16] Started run 437 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:16] Started run 438 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:16] Error in run 431: Run already exists in server. Run id(s): {9030661}
[2018-04-11 20:46:16] Started run 439 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:17] Error in run 432: Run already exists in server. Run id(s): {9030669}
[2018-04-11 20:46:17] Started run 440 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:18] Error in run 433: Run already exists in server. Run id(s): {9030679}
[2018-04-11 20:46:18] Started run 441 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:19] Error in run 434: Run already exists in server. Run id(s): {9030783}
[2018-04-11 20:46:19] Started run 442 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:20] Error in run 435: Run already exists in server. Run id(s): {9030737}
[2018-04-11 20:46:20] Started run 443 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:20] Error in run 436: Run already exists in server. Run id(s): {9030697}
[2018-04-11 20:46:20] Started run 444 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:20] Error in run 438: Run already exists in server. Run id(s): {9030723}
[2018-04-11 20:46:20] Started run 445 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:21] Error in run 437: Run already exists in server. Run id(s): {9030704}
[2018-04-11 20:46:21] Started run 446 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:21] Error in run 439: Run already exists in server. Run id(s): {9030708}
[2018-04-11 20:46:21] Started run 447 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:21] Error in run 440: Run already exists in server. Run id(s): {9030722}
[2018-04-11 20:46:21] Started run 448 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:23] Error in run 441: Run already exists in server. Run id(s): {9030760}
[2018-04-11 20:46:23] Started run 449 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:23] Error in run 442: Run already exists in server. Run id(s): {9030754}
[2018-04-11 20:46:23] Started run 450 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:24] Error in run 443: Run already exists in server. Run id(s): {9030765}
[2018-04-11 20:46:24] Started run 451 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:25] Error in run 444: Run already exists in server. Run id(s): {9030778}
[2018-04-11 20:46:25] Started run 452 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:25] Error in run 445: Run already exists in server. Run id(s): {9030774}
[2018-04-11 20:46:25] Started run 453 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:25] Error in run 446: Run already exists in server. Run id(s): {9030780}
[2018-04-11 20:46:25] Started run 454 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:25] Error in run 447: Run already exists in server. Run id(s): {9030811}
[2018-04-11 20:46:25] Started run 455 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:26] Error in run 448: Run already exists in server. Run id(s): {9030804}
[2018-04-11 20:46:26] Started run 456 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:27] Error in run 449: Run already exists in server. Run id(s): {9030815}
[2018-04-11 20:46:27] Started run 457 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:28] Error in run 450: Run already exists in server. Run id(s): {9030814}
[2018-04-11 20:46:28] Started run 458 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:29] Error in run 451: Run already exists in server. Run id(s): {9030830}
[2018-04-11 20:46:29] Started run 459 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:30] Error in run 452: Run already exists in server. Run id(s): {9030823}
[2018-04-11 20:46:30] Started run 460 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:30] Error in run 453: Run already exists in server. Run id(s): {9030829}
[2018-04-11 20:46:30] Started run 461 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:30] Error in run 455: Run already exists in server. Run id(s): {9030848}
[2018-04-11 20:46:30] Started run 462 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:30] Error in run 454: Run already exists in server. Run id(s): {9030826}
[2018-04-11 20:46:30] Started run 463 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:31] Error in run 456: Run already exists in server. Run id(s): {9030869}
[2018-04-11 20:46:31] Started run 464 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:32] Error in run 457: Run already exists in server. Run id(s): {9030867}
[2018-04-11 20:46:32] Started run 465 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:32] Error in run 458: Run already exists in server. Run id(s): {9030865}
[2018-04-11 20:46:32] Started run 466 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:34] Error in run 459: Run already exists in server. Run id(s): {9030875}
[2018-04-11 20:46:34] Started run 467 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:34] Error in run 461: Run already exists in server. Run id(s): {9030895}
[2018-04-11 20:46:34] Started run 468 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:34] Error in run 460: Run already exists in server. Run id(s): {9030881}
[2018-04-11 20:46:34] Started run 469 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:35] Error in run 463: Run already exists in server. Run id(s): {9030910}
[2018-04-11 20:46:35] Started run 470 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:35] Error in run 462: Run already exists in server. Run id(s): {9030898}
[2018-04-11 20:46:35] Started run 471 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:35] Error in run 464: Run already exists in server. Run id(s): {9030940}
[2018-04-11 20:46:35] Started run 472 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:37] Error in run 465: Run already exists in server. Run id(s): {9030922}
[2018-04-11 20:46:37] Started run 473 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:37] Error in run 466: Run already exists in server. Run id(s): {9030928}
[2018-04-11 20:46:37] Started run 474 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:38] Error in run 467: Run already exists in server. Run id(s): {9030933}
[2018-04-11 20:46:38] Started run 475 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:39] Error in run 468: Run already exists in server. Run id(s): {9030939}
[2018-04-11 20:46:39] Started run 476 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:39] Error in run 469: Run already exists in server. Run id(s): {9030946}
[2018-04-11 20:46:39] Started run 477 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:39] Error in run 470: Run already exists in server. Run id(s): {9030950}
[2018-04-11 20:46:39] Started run 478 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:39] Error in run 471: Run already exists in server. Run id(s): {9030965}
[2018-04-11 20:46:39] Started run 479 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:40] Error in run 472: Run already exists in server. Run id(s): {9030980}
[2018-04-11 20:46:40] Started run 480 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:41] Error in run 473: Run already exists in server. Run id(s): {9030994}
[2018-04-11 20:46:41] Started run 481 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:42] Error in run 474: Run already exists in server. Run id(s): {9030983}
[2018-04-11 20:46:42] Started run 482 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:43] Error in run 475: Run already exists in server. Run id(s): {9030989}
[2018-04-11 20:46:43] Started run 483 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:43] Error in run 476: Run already exists in server. Run id(s): {9030997}
[2018-04-11 20:46:43] Started run 484 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:43] Error in run 477: Run already exists in server. Run id(s): {9031003}
[2018-04-11 20:46:43] Started run 485 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:44] Error in run 478: Run already exists in server. Run id(s): {9031010}
[2018-04-11 20:46:44] Started run 486 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:44] Error in run 479: Run already exists in server. Run id(s): {9031017}
[2018-04-11 20:46:44] Started run 487 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:45] Error in run 480: Run already exists in server. Run id(s): {9031033}
[2018-04-11 20:46:45] Started run 488 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:46] Error in run 481: Run already exists in server. Run id(s): {9031027}
[2018-04-11 20:46:46] Started run 489 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:46] Error in run 482: Run already exists in server. Run id(s): {9031037}
[2018-04-11 20:46:46] Started run 490 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:47] Error in run 483: Run already exists in server. Run id(s): {9031042}
[2018-04-11 20:46:47] Started run 491 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:48] Error in run 485: Run already exists in server. Run id(s): {9031053}
[2018-04-11 20:46:48] Started run 492 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:48] Error in run 484: Run already exists in server. Run id(s): {9031052}
[2018-04-11 20:46:48] Started run 493 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:48] Error in run 486: Run already exists in server. Run id(s): {9031057}
[2018-04-11 20:46:48] Started run 494 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:48] Error in run 487: Run already exists in server. Run id(s): {9031068}
[2018-04-11 20:46:48] Started run 495 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:49] Error in run 488: Run already exists in server. Run id(s): {9031067}
[2018-04-11 20:46:49] Started run 496 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:50] Error in run 489: Run already exists in server. Run id(s): {9031083}
[2018-04-11 20:46:50] Started run 497 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:51] Error in run 490: Run already exists in server. Run id(s): {9031073}
[2018-04-11 20:46:51] Started run 498 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:52] Error in run 491: Run already exists in server. Run id(s): {9031084}
[2018-04-11 20:46:52] Started run 499 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:53] Error in run 492: Run already exists in server. Run id(s): {9031092}
[2018-04-11 20:46:53] Started run 500 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:53] Error in run 493: Run already exists in server. Run id(s): {9031111}
[2018-04-11 20:46:53] Started run 501 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:53] Error in run 494: Run already exists in server. Run id(s): {9031107}
[2018-04-11 20:46:53] Started run 502 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:53] Error in run 495: Run already exists in server. Run id(s): {9031119}
[2018-04-11 20:46:53] Started run 503 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:54] Error in run 496: Run already exists in server. Run id(s): {9031120}
[2018-04-11 20:46:54] Started run 504 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:55] Error in run 497: Run already exists in server. Run id(s): {9031138}
[2018-04-11 20:46:55] Started run 505 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:55] Error in run 498: Run already exists in server. Run id(s): {9031136}
[2018-04-11 20:46:55] Started run 506 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:56] Error in run 499: Run already exists in server. Run id(s): {9031142}
[2018-04-11 20:46:56] Started run 507 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:57] Error in run 502: Run already exists in server. Run id(s): {9031156}
[2018-04-11 20:46:57] Started run 508 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:57] Error in run 501: Run already exists in server. Run id(s): {9031155}
[2018-04-11 20:46:57] Error in run 500: Run already exists in server. Run id(s): {9031154}
[2018-04-11 20:46:57] Started run 509 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:57] Started run 510 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:57] Error in run 503: Run already exists in server. Run id(s): {9031183}
[2018-04-11 20:46:57] Started run 511 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:58] Error in run 504: Run already exists in server. Run id(s): {9031175}
[2018-04-11 20:46:58] Started run 512 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:46:59] Error in run 505: Run already exists in server. Run id(s): {9031180}
[2018-04-11 20:46:59] Started run 513 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:00] Error in run 506: Run already exists in server. Run id(s): {9031189}
[2018-04-11 20:47:00] Started run 514 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:01] Error in run 507: Run already exists in server. Run id(s): {9031205}
[2018-04-11 20:47:01] Started run 515 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:02] Error in run 508: Run already exists in server. Run id(s): {9031198}
[2018-04-11 20:47:02] Started run 516 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:02] Error in run 509: Run already exists in server. Run id(s): {9031211}
[2018-04-11 20:47:02] Started run 517 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:02] Error in run 510: Run already exists in server. Run id(s): {9031202}
[2018-04-11 20:47:02] Started run 518 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:02] Error in run 511: Run already exists in server. Run id(s): {9031217}
[2018-04-11 20:47:02] Started run 519 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:03] Error in run 512: Run already exists in server. Run id(s): {9031216}
[2018-04-11 20:47:03] Started run 520 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:04] Error in run 513: Run already exists in server. Run id(s): {9031228}
[2018-04-11 20:47:04] Started run 521 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:04] Error in run 514: Run already exists in server. Run id(s): {9031224}
[2018-04-11 20:47:04] Started run 522 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:05] Error in run 515: Run already exists in server. Run id(s): {9031243}
[2018-04-11 20:47:05] Started run 523 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:06] Error in run 516: Run already exists in server. Run id(s): {9031262}
[2018-04-11 20:47:06] Started run 524 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:06] Error in run 517: Run already exists in server. Run id(s): {9031244}
[2018-04-11 20:47:06] Started run 525 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:06] Error in run 518: Run already exists in server. Run id(s): {9031260}
[2018-04-11 20:47:06] Started run 526 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:07] Error in run 519: Run already exists in server. Run id(s): {9031257}
[2018-04-11 20:47:07] Started run 527 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:07] Error in run 520: Run already exists in server. Run id(s): {9031266}
[2018-04-11 20:47:07] Started run 528 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:08] Error in run 521: Run already exists in server. Run id(s): {9031267}
[2018-04-11 20:47:08] Started run 529 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:09] Error in run 522: Run already exists in server. Run id(s): {9031284}
[2018-04-11 20:47:09] Started run 530 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:10] Error in run 523: Run already exists in server. Run id(s): {9031289}
[2018-04-11 20:47:10] Started run 531 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:11] Error in run 524: Run already exists in server. Run id(s): {9031287}
[2018-04-11 20:47:11] Started run 532 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:11] Error in run 525: Run already exists in server. Run id(s): {9031299}
[2018-04-11 20:47:11] Started run 533 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:11] Error in run 526: Run already exists in server. Run id(s): {9031320}
[2018-04-11 20:47:11] Started run 534 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:11] Error in run 527: Run already exists in server. Run id(s): {9031324}
[2018-04-11 20:47:11] Started run 535 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:12] Error in run 528: Run already exists in server. Run id(s): {9031302}
[2018-04-11 20:47:12] Started run 536 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:13] Error in run 529: Run already exists in server. Run id(s): {9031313}
[2018-04-11 20:47:13] Started run 537 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:13] Error in run 530: Run already exists in server. Run id(s): {9031343}
[2018-04-11 20:47:13] Started run 538 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:14] Error in run 531: Run already exists in server. Run id(s): {9031335}
[2018-04-11 20:47:14] Started run 539 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:15] Error in run 532: Run already exists in server. Run id(s): {9031331}
[2018-04-11 20:47:15] Started run 540 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:15] Error in run 533: Run already exists in server. Run id(s): {9031347}
[2018-04-11 20:47:15] Started run 541 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:15] Error in run 534: Run already exists in server. Run id(s): {9031362}
[2018-04-11 20:47:15] Started run 542 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:16] Error in run 535: Run already exists in server. Run id(s): {9031352}
[2018-04-11 20:47:16] Started run 543 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:16] Error in run 536: Run already exists in server. Run id(s): {9031353}
[2018-04-11 20:47:16] Started run 544 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:17] Error in run 537: Run already exists in server. Run id(s): {9031367}
[2018-04-11 20:47:17] Started run 545 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:18] Error in run 538: Run already exists in server. Run id(s): {9031374}
[2018-04-11 20:47:18] Started run 546 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:19] Error in run 539: Run already exists in server. Run id(s): {9031378}
[2018-04-11 20:47:19] Started run 547 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:20] Error in run 542: Run already exists in server. Run id(s): {9031394}
[2018-04-11 20:47:20] Error in run 541: Run already exists in server. Run id(s): {9031392}
[2018-04-11 20:47:20] Started run 548 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:20] Error in run 540: Run already exists in server. Run id(s): {9031380}
[2018-04-11 20:47:20] Started run 550 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:20] Started run 549 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:20] Error in run 543: Run already exists in server. Run id(s): {9031400}
[2018-04-11 20:47:20] Started run 551 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:21] Error in run 544: Run already exists in server. Run id(s): {9031411}
[2018-04-11 20:47:21] Started run 552 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:22] Error in run 545: Run already exists in server. Run id(s): {9031410}
[2018-04-11 20:47:22] Started run 553 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:22] Error in run 546: Run already exists in server. Run id(s): {9031419}
[2018-04-11 20:47:22] Started run 554 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:23] Error in run 547: Run already exists in server. Run id(s): {9031420}
[2018-04-11 20:47:23] Started run 555 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:24] Error in run 548: Run already exists in server. Run id(s): {9031423}
[2018-04-11 20:47:24] Started run 556 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:25] Error in run 549: Run already exists in server. Run id(s): {9031436}
[2018-04-11 20:47:25] Started run 557 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:25] Error in run 550: Run already exists in server. Run id(s): {9031441}
[2018-04-11 20:47:25] Started run 558 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:25] Error in run 551: Run already exists in server. Run id(s): {9031437}
[2018-04-11 20:47:25] Started run 559 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:25] Error in run 552: Run already exists in server. Run id(s): {9031454}
[2018-04-11 20:47:25] Started run 560 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:27] Error in run 553: Run already exists in server. Run id(s): {9031452}
[2018-04-11 20:47:27] Started run 561 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:27] Error in run 554: Run already exists in server. Run id(s): {9031465}
[2018-04-11 20:47:27] Started run 562 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:28] Error in run 555: Run already exists in server. Run id(s): {9031467}
[2018-04-11 20:47:28] Started run 563 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:29] Error in run 556: Run already exists in server. Run id(s): {9031466}
[2018-04-11 20:47:29] Started run 564 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:29] Error in run 557: Run already exists in server. Run id(s): {9031480}
[2018-04-11 20:47:29] Started run 565 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:29] Error in run 558: Run already exists in server. Run id(s): {9031485}
[2018-04-11 20:47:29] Started run 566 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:30] Error in run 559: Run already exists in server. Run id(s): {9031492}
[2018-04-11 20:47:30] Started run 567 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:30] Error in run 560: Run already exists in server. Run id(s): {9031494}
[2018-04-11 20:47:30] Started run 568 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:31] Error in run 561: Run already exists in server. Run id(s): {9031510}
[2018-04-11 20:47:31] Started run 569 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:31] Error in run 562: Run already exists in server. Run id(s): {9031503}
[2018-04-11 20:47:31] Started run 570 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:32] Error in run 563: Run already exists in server. Run id(s): {9031506}
[2018-04-11 20:47:32] Started run 571 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:34] Error in run 565: Run already exists in server. Run id(s): {9031524}
[2018-04-11 20:47:34] Error in run 564: Run already exists in server. Run id(s): {9031516}
[2018-04-11 20:47:34] Started run 572 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:34] Started run 573 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:34] Error in run 566: Run already exists in server. Run id(s): {9031540}
[2018-04-11 20:47:34] Started run 574 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:34] Error in run 567: Run already exists in server. Run id(s): {9031538}
[2018-04-11 20:47:34] Started run 575 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:35] Error in run 568: Run already exists in server. Run id(s): {9031532}
[2018-04-11 20:47:35] Started run 576 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:36] Error in run 569: Run already exists in server. Run id(s): {9031542}
[2018-04-11 20:47:36] Started run 577 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:36] Error in run 570: Run already exists in server. Run id(s): {9031548}
[2018-04-11 20:47:36] Started run 578 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:37] Error in run 571: Run already exists in server. Run id(s): {9031554}
[2018-04-11 20:47:37] Started run 579 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:38] Error in run 572: Run already exists in server. Run id(s): {9031555}
[2018-04-11 20:47:38] Error in run 573: Run already exists in server. Run id(s): {9031569}
[2018-04-11 20:47:38] Started run 580 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:38] Started run 581 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:38] Error in run 574: Run already exists in server. Run id(s): {9031567}
[2018-04-11 20:47:38] Started run 582 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:39] Error in run 575: Run already exists in server. Run id(s): {9031572}
[2018-04-11 20:47:39] Started run 583 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:39] Error in run 576: Run already exists in server. Run id(s): {9031575}
[2018-04-11 20:47:39] Started run 584 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:40] Error in run 577: Run already exists in server. Run id(s): {9031582}
[2018-04-11 20:47:40] Started run 585 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:40] Error in run 578: Run already exists in server. Run id(s): {9031587}
[2018-04-11 20:47:40] Started run 586 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:41] Error in run 579: Run already exists in server. Run id(s): {9031600}
[2018-04-11 20:47:41] Started run 587 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:43] Error in run 581: Run already exists in server. Run id(s): {9031607}
[2018-04-11 20:47:43] Started run 588 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:43] Error in run 580: Run already exists in server. Run id(s): {9031599}
[2018-04-11 20:47:43] Started run 589 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:43] Error in run 582: Run already exists in server. Run id(s): {9031614}
[2018-04-11 20:47:43] Started run 590 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:43] Error in run 583: Run already exists in server. Run id(s): {9031618}
[2018-04-11 20:47:43] Started run 591 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:44] Error in run 584: Run already exists in server. Run id(s): {9031617}
[2018-04-11 20:47:44] Started run 592 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:45] Error in run 585: Run already exists in server. Run id(s): {9031628}
[2018-04-11 20:47:45] Started run 593 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:45] Error in run 586: Run already exists in server. Run id(s): {9031639}
[2018-04-11 20:47:45] Started run 594 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:46] Error in run 587: Run already exists in server. Run id(s): {9031649}
[2018-04-11 20:47:46] Started run 595 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:47] Error in run 588: Run already exists in server. Run id(s): {9031650}
[2018-04-11 20:47:47] Error in run 590: Run already exists in server. Run id(s): {9031666}
[2018-04-11 20:47:47] Error in run 589: Run already exists in server. Run id(s): {9031660}
[2018-04-11 20:47:47] Started run 596 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:47] Started run 598 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:47] Started run 597 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:48] Error in run 591: Run already exists in server. Run id(s): {9031683}
[2018-04-11 20:47:48] Started run 599 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:48] Error in run 592: Run already exists in server. Run id(s): {9031675}
[2018-04-11 20:47:48] Started run 600 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:49] Error in run 594: Run already exists in server. Run id(s): {9031682}
[2018-04-11 20:47:50] Error in run 593: Run already exists in server. Run id(s): {9031681}
[2018-04-11 20:47:49] Started run 601 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:50] Started run 602 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:50] Error in run 595: Run already exists in server. Run id(s): {9031697}
[2018-04-11 20:47:50] Started run 603 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:52] Error in run 597: Run already exists in server. Run id(s): {9031706}
[2018-04-11 20:47:52] Started run 604 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:52] Error in run 598: Run already exists in server. Run id(s): {9031725}
[2018-04-11 20:47:52] Started run 605 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:52] Error in run 596: Run already exists in server. Run id(s): {9031694}
[2018-04-11 20:47:52] Started run 606 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:53] Error in run 600: Run already exists in server. Run id(s): {9031717}
[2018-04-11 20:47:53] Error in run 599: Run already exists in server. Run id(s): {9031714}
[2018-04-11 20:47:53] Started run 607 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:53] Started run 608 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:54] Error in run 602: Run already exists in server. Run id(s): {9031738}
[2018-04-11 20:47:54] Started run 609 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:54] Error in run 601: Run already exists in server. Run id(s): {9031727}
[2018-04-11 20:47:54] Started run 610 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:55] Error in run 603: Run already exists in server. Run id(s): {9031735}
[2018-04-11 20:47:55] Started run 611 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:57] Error in run 604: Run already exists in server. Run id(s): {9031732}
[2018-04-11 20:47:57] Started run 612 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:57] Error in run 606: Run already exists in server. Run id(s): {9031755}
[2018-04-11 20:47:57] Error in run 605: Run already exists in server. Run id(s): {9031765}
[2018-04-11 20:47:57] Started run 614 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:57] Started run 613 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:57] Error in run 608: Run already exists in server. Run id(s): {9031768}
[2018-04-11 20:47:57] Started run 615 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:57] Error in run 607: Run already exists in server. Run id(s): {9031758}
[2018-04-11 20:47:57] Started run 616 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:59] Error in run 609: Run already exists in server. Run id(s): {9031771}
[2018-04-11 20:47:59] Started run 617 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:47:59] Error in run 610: Run already exists in server. Run id(s): {9031790}
[2018-04-11 20:47:59] Started run 618 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:00] Error in run 611: Run already exists in server. Run id(s): {9031786}
[2018-04-11 20:48:00] Started run 619 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:01] Error in run 612: Run already exists in server. Run id(s): {9031802}
[2018-04-11 20:48:01] Started run 620 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:01] Error in run 614: Run already exists in server. Run id(s): {9031804}
[2018-04-11 20:48:01] Started run 621 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:01] Error in run 613: Run already exists in server. Run id(s): {9031806}
[2018-04-11 20:48:01] Started run 622 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:02] Error in run 615: Run already exists in server. Run id(s): {9031811}
[2018-04-11 20:48:02] Started run 623 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:02] Error in run 616: Run already exists in server. Run id(s): {9031818}
[2018-04-11 20:48:02] Started run 624 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:03] Error in run 617: Run already exists in server. Run id(s): {9031821}
[2018-04-11 20:48:03] Started run 625 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:04] Error in run 618: Run already exists in server. Run id(s): {9031837}
[2018-04-11 20:48:04] Started run 626 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:04] Error in run 619: Run already exists in server. Run id(s): {9031850}
[2018-04-11 20:48:04] Started run 627 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:06] Error in run 620: Run already exists in server. Run id(s): {9031848}
[2018-04-11 20:48:06] Started run 628 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:06] Error in run 621: Run already exists in server. Run id(s): {9031875}
[2018-04-11 20:48:06] Error in run 622: Run already exists in server. Run id(s): {9031859}
[2018-04-11 20:48:06] Started run 629 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:06] Started run 630 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:06] Error in run 623: Run already exists in server. Run id(s): {9031862}
[2018-04-11 20:48:06] Started run 631 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:07] Error in run 624: Run already exists in server. Run id(s): {9031864}
[2018-04-11 20:48:07] Started run 632 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:08] Error in run 625: Run already exists in server. Run id(s): {9031872}
[2018-04-11 20:48:08] Started run 633 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:08] Error in run 626: Run already exists in server. Run id(s): {9031894}
[2018-04-11 20:48:08] Started run 634 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:09] Error in run 627: Run already exists in server. Run id(s): {9031897}
[2018-04-11 20:48:09] Started run 635 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:10] Error in run 628: Run already exists in server. Run id(s): {9031901}
[2018-04-11 20:48:10] Started run 636 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:11] Error in run 630: Run already exists in server. Run id(s): {9031912}
[2018-04-11 20:48:11] Error in run 629: Run already exists in server. Run id(s): {9031909}
[2018-04-11 20:48:11] Started run 638 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:11] Started run 637 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:11] Error in run 631: Run already exists in server. Run id(s): {9031917}
[2018-04-11 20:48:11] Started run 639 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:11] Error in run 632: Run already exists in server. Run id(s): {9031924}
[2018-04-11 20:48:11] Started run 640 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:12] Error in run 633: Run already exists in server. Run id(s): {9031943}
[2018-04-11 20:48:12] Started run 641 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:13] Error in run 634: Run already exists in server. Run id(s): {9031939}
[2018-04-11 20:48:13] Started run 642 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:14] Error in run 635: Run already exists in server. Run id(s): {9031938}
[2018-04-11 20:48:14] Started run 643 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:15] Error in run 636: Run already exists in server. Run id(s): {9031954}
[2018-04-11 20:48:15] Started run 644 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:15] Error in run 637: Run already exists in server. Run id(s): {9031953}
[2018-04-11 20:48:15] Error in run 638: Run already exists in server. Run id(s): {9031966}
[2018-04-11 20:48:15] Started run 645 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:15] Started run 646 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:15] Error in run 639: Run already exists in server. Run id(s): {9031972}
[2018-04-11 20:48:15] Started run 647 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:16] Error in run 640: Run already exists in server. Run id(s): {9031986}
[2018-04-11 20:48:16] Started run 648 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:17] Error in run 641: Run already exists in server. Run id(s): {9032075}
[2018-04-11 20:48:17] Started run 649 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:17] Error in run 642: Run already exists in server. Run id(s): {9032078}
[2018-04-11 20:48:17] Started run 650 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:18] Error in run 643: Run already exists in server. Run id(s): {9031998}
[2018-04-11 20:48:18] Started run 651 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:19] Error in run 644: Run already exists in server. Run id(s): {9032007}
[2018-04-11 20:48:19] Started run 652 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:20] Error in run 645: Run already exists in server. Run id(s): {9032013}
[2018-04-11 20:48:20] Started run 653 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:20] Error in run 646: Run already exists in server. Run id(s): {9032020}
[2018-04-11 20:48:20] Started run 654 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:20] Error in run 647: Run already exists in server. Run id(s): {9032037}
[2018-04-11 20:48:20] Started run 655 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:20] Error in run 648: Run already exists in server. Run id(s): {9032033}
[2018-04-11 20:48:20] Started run 656 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:21] Error in run 649: Run already exists in server. Run id(s): {9032048}
[2018-04-11 20:48:21] Started run 657 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:22] Error in run 650: Run already exists in server. Run id(s): {9032069}
[2018-04-11 20:48:22] Started run 658 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:23] Error in run 651: Run already exists in server. Run id(s): {9032070}
[2018-04-11 20:48:23] Started run 659 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:24] Error in run 652: Run already exists in server. Run id(s): {9032076}
[2018-04-11 20:48:24] Started run 660 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:24] Error in run 654: Run already exists in server. Run id(s): {9032086}
[2018-04-11 20:48:24] Error in run 653: Run already exists in server. Run id(s): {9032095}
[2018-04-11 20:48:24] Started run 661 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:24] Started run 662 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:24] Error in run 655: Run already exists in server. Run id(s): {9032107}
[2018-04-11 20:48:24] Started run 663 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:25] Error in run 656: Run already exists in server. Run id(s): {9032136}
[2018-04-11 20:48:25] Started run 664 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:26] Error in run 657: Run already exists in server. Run id(s): {9032121}
[2018-04-11 20:48:26] Started run 665 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:26] Error in run 658: Run already exists in server. Run id(s): {9032124}
[2018-04-11 20:48:26] Started run 666 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:27] Error in run 659: Run already exists in server. Run id(s): {9032133}
[2018-04-11 20:48:27] Started run 667 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:28] Error in run 660: Run already exists in server. Run id(s): {9032144}
[2018-04-11 20:48:28] Started run 668 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:29] Error in run 662: Run already exists in server. Run id(s): {9032150}
[2018-04-11 20:48:29] Started run 669 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:29] Error in run 661: Run already exists in server. Run id(s): {9032142}
[2018-04-11 20:48:29] Started run 670 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:29] Error in run 663: Run already exists in server. Run id(s): {9032157}
[2018-04-11 20:48:29] Started run 671 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:29] Error in run 664: Run already exists in server. Run id(s): {9032180}
[2018-04-11 20:48:29] Started run 672 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:30] Error in run 665: Run already exists in server. Run id(s): {9032176}
[2018-04-11 20:48:30] Started run 673 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:31] Error in run 666: Run already exists in server. Run id(s): {9032186}
[2018-04-11 20:48:31] Started run 674 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:32] Error in run 667: Run already exists in server. Run id(s): {9032192}
[2018-04-11 20:48:32] Started run 675 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:33] Error in run 668: Run already exists in server. Run id(s): {9032200}
[2018-04-11 20:48:33] Started run 676 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:33] Error in run 669: Run already exists in server. Run id(s): {9032204}
[2018-04-11 20:48:33] Started run 677 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:33] Error in run 670: Run already exists in server. Run id(s): {9032209}
[2018-04-11 20:48:33] Started run 678 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:33] Error in run 671: Run already exists in server. Run id(s): {9032211}
[2018-04-11 20:48:33] Started run 679 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:34] Error in run 672: Run already exists in server. Run id(s): {9032236}
[2018-04-11 20:48:34] Started run 680 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:35] Error in run 673: Run already exists in server. Run id(s): {9032239}
[2018-04-11 20:48:35] Started run 681 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:35] Error in run 674: Run already exists in server. Run id(s): {9032265}
[2018-04-11 20:48:35] Started run 682 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:36] Error in run 675: Run already exists in server. Run id(s): {9032243}
[2018-04-11 20:48:36] Started run 683 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:37] Error in run 676: Run already exists in server. Run id(s): {9032277}
[2018-04-11 20:48:37] Started run 684 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:38] Error in run 677: Run already exists in server. Run id(s): {9032270}
[2018-04-11 20:48:38] Started run 685 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:38] Error in run 678: Run already exists in server. Run id(s): {9032285}
[2018-04-11 20:48:38] Started run 686 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:38] Error in run 679: Run already exists in server. Run id(s): {9032276}
[2018-04-11 20:48:38] Started run 687 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:38] Error in run 680: Run already exists in server. Run id(s): {9032322}
[2018-04-11 20:48:38] Started run 688 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:39] Error in run 681: Run already exists in server. Run id(s): {9032333}
[2018-04-11 20:48:39] Started run 689 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:40] Error in run 682: Run already exists in server. Run id(s): {9032308}
[2018-04-11 20:48:40] Started run 690 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:41] Error in run 683: Run already exists in server. Run id(s): {9032336}
[2018-04-11 20:48:41] Started run 691 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:42] Error in run 684: Run already exists in server. Run id(s): {9032321}
[2018-04-11 20:48:42] Started run 692 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:42] Error in run 685: Run already exists in server. Run id(s): {9032331}
[2018-04-11 20:48:42] Started run 693 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:42] Error in run 686: Run already exists in server. Run id(s): {9032319}
[2018-04-11 20:48:42] Started run 694 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:42] Error in run 687: Run already exists in server. Run id(s): {9032327}
[2018-04-11 20:48:42] Started run 695 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:43] Error in run 688: Run already exists in server. Run id(s): {9032356}
[2018-04-11 20:48:43] Started run 696 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:44] Error in run 689: Run already exists in server. Run id(s): {9032373}
[2018-04-11 20:48:44] Started run 697 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:44] Error in run 690: Run already exists in server. Run id(s): {9032375}
[2018-04-11 20:48:44] Started run 698 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:45] Error in run 691: Run already exists in server. Run id(s): {9032376}
[2018-04-11 20:48:45] Started run 699 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:47] Error in run 692: Run already exists in server. Run id(s): {9032378}
[2018-04-11 20:48:47] Started run 700 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:47] Error in run 693: Run already exists in server. Run id(s): {9032391}
[2018-04-11 20:48:47] Started run 701 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:47] Error in run 694: Run already exists in server. Run id(s): {9032389}
[2018-04-11 20:48:47] Started run 702 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:47] Error in run 695: Run already exists in server. Run id(s): {9032397}
[2018-04-11 20:48:47] Started run 703 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:47] Error in run 696: Run already exists in server. Run id(s): {9032400}
[2018-04-11 20:48:47] Started run 704 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:48] Error in run 697: Run already exists in server. Run id(s): {9032418}
[2018-04-11 20:48:48] Started run 705 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:49] Error in run 698: Run already exists in server. Run id(s): {9032433}
[2018-04-11 20:48:49] Started run 706 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:50] Error in run 699: Run already exists in server. Run id(s): {9032431}
[2018-04-11 20:48:50] Started run 707 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:51] Error in run 701: Run already exists in server. Run id(s): {9032441}
[2018-04-11 20:48:51] Started run 708 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:51] Error in run 700: Run already exists in server. Run id(s): {9032424}
[2018-04-11 20:48:51] Started run 709 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:51] Error in run 702: Run already exists in server. Run id(s): {9032458}
[2018-04-11 20:48:51] Started run 710 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:51] Error in run 703: Run already exists in server. Run id(s): {9032457}
[2018-04-11 20:48:51] Started run 711 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:52] Error in run 704: Run already exists in server. Run id(s): {9032450}
[2018-04-11 20:48:52] Started run 712 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:53] Error in run 705: Run already exists in server. Run id(s): {9032488}
[2018-04-11 20:48:53] Started run 713 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:53] Error in run 706: Run already exists in server. Run id(s): {9032492}
[2018-04-11 20:48:53] Started run 714 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:54] Error in run 707: Run already exists in server. Run id(s): {9032484}
[2018-04-11 20:48:54] Started run 715 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:56] Error in run 708: Run already exists in server. Run id(s): {9032496}
[2018-04-11 20:48:56] Error in run 709: Run already exists in server. Run id(s): {9032499}
[2018-04-11 20:48:56] Started run 716 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:56] Started run 717 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:56] Error in run 710: Run already exists in server. Run id(s): {9032508}
[2018-04-11 20:48:56] Started run 718 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:56] Error in run 711: Run already exists in server. Run id(s): {9032516}
[2018-04-11 20:48:56] Started run 719 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:56] Error in run 712: Run already exists in server. Run id(s): {9032511}
[2018-04-11 20:48:56] Started run 720 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:57] Error in run 713: Run already exists in server. Run id(s): {9032532}
[2018-04-11 20:48:57] Started run 721 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:58] Error in run 714: Run already exists in server. Run id(s): {9032535}
[2018-04-11 20:48:58] Started run 722 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:48:59] Error in run 715: Run already exists in server. Run id(s): {9032542}
[2018-04-11 20:48:59] Started run 723 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:00] Error in run 716: Run already exists in server. Run id(s): {9032544}
[2018-04-11 20:49:00] Started run 724 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:00] Error in run 717: Run already exists in server. Run id(s): {9032545}
[2018-04-11 20:49:00] Started run 725 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:01] Error in run 719: Run already exists in server. Run id(s): {9032577}
[2018-04-11 20:49:01] Started run 726 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:01] Error in run 718: Run already exists in server. Run id(s): {9032580}
[2018-04-11 20:49:01] Started run 727 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:01] Error in run 720: Run already exists in server. Run id(s): {9032569}
[2018-04-11 20:49:01] Started run 728 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:02] Error in run 721: Run already exists in server. Run id(s): {9032585}
[2018-04-11 20:49:02] Started run 729 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:02] Error in run 722: Run already exists in server. Run id(s): {9032589}
[2018-04-11 20:49:02] Started run 730 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:04] Error in run 723: Run already exists in server. Run id(s): {9032608}
[2018-04-11 20:49:04] Started run 731 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:05] Error in run 724: Run already exists in server. Run id(s): {9032600}
[2018-04-11 20:49:05] Started run 732 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:05] Error in run 725: Run already exists in server. Run id(s): {9032647}
[2018-04-11 20:49:05] Started run 733 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:05] Error in run 726: Run already exists in server. Run id(s): {9032632}
[2018-04-11 20:49:05] Started run 734 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:05] Error in run 727: Run already exists in server. Run id(s): {9032631}
[2018-04-11 20:49:05] Started run 735 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:06] Error in run 728: Run already exists in server. Run id(s): {9032686}
[2018-04-11 20:49:06] Started run 736 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:07] Error in run 729: Run already exists in server. Run id(s): {9032639}
[2018-04-11 20:49:07] Started run 737 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:07] Error in run 730: Run already exists in server. Run id(s): {9032637}
[2018-04-11 20:49:07] Started run 738 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:08] Error in run 731: Run already exists in server. Run id(s): {9032650}
[2018-04-11 20:49:08] Started run 739 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:09] Error in run 732: Run already exists in server. Run id(s): {9032657}
[2018-04-11 20:49:09] Started run 740 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:09] Error in run 733: Run already exists in server. Run id(s): {9032678}
[2018-04-11 20:49:09] Started run 741 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:09] Error in run 735: Run already exists in server. Run id(s): {9032756}
[2018-04-11 20:49:09] Started run 742 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:10] Error in run 734: Run already exists in server. Run id(s): {9032693}
[2018-04-11 20:49:10] Started run 743 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:10] Error in run 736: Run already exists in server. Run id(s): {9032695}
[2018-04-11 20:49:10] Started run 744 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:11] Error in run 737: Run already exists in server. Run id(s): {9032708}
[2018-04-11 20:49:11] Started run 745 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:12] Error in run 738: Run already exists in server. Run id(s): {9032717}
[2018-04-11 20:49:12] Started run 746 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:13] Error in run 739: Run already exists in server. Run id(s): {9032718}
[2018-04-11 20:49:13] Started run 747 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:14] Error in run 740: Run already exists in server. Run id(s): {9032724}
[2018-04-11 20:49:14] Started run 748 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:14] Error in run 741: Run already exists in server. Run id(s): {9032731}
[2018-04-11 20:49:14] Started run 749 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:14] Error in run 743: Run already exists in server. Run id(s): {9032736}
[2018-04-11 20:49:14] Started run 750 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:14] Error in run 742: Run already exists in server. Run id(s): {9032730}
[2018-04-11 20:49:14] Started run 751 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:15] Error in run 744: Run already exists in server. Run id(s): {9032769}
[2018-04-11 20:49:15] Started run 752 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:16] Error in run 745: Run already exists in server. Run id(s): {9032762}
[2018-04-11 20:49:16] Started run 753 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:16] Error in run 746: Run already exists in server. Run id(s): {9032779}
[2018-04-11 20:49:16] Started run 754 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:17] Error in run 747: Run already exists in server. Run id(s): {9032780}
[2018-04-11 20:49:17] Started run 755 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:19] Error in run 748: Run already exists in server. Run id(s): {9032773}
[2018-04-11 20:49:19] Started run 756 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:19] Error in run 749: Run already exists in server. Run id(s): {9032782}
[2018-04-11 20:49:19] Error in run 750: Run already exists in server. Run id(s): {9032788}
[2018-04-11 20:49:19] Started run 757 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:19] Started run 758 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:19] Error in run 751: Run already exists in server. Run id(s): {9032824}
[2018-04-11 20:49:19] Started run 759 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:19] Error in run 752: Run already exists in server. Run id(s): {9032817}
[2018-04-11 20:49:19] Started run 760 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:20] Error in run 753: Run already exists in server. Run id(s): {9032847}
[2018-04-11 20:49:20] Started run 761 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:21] Error in run 754: Run already exists in server. Run id(s): {9032838}
[2018-04-11 20:49:21] Started run 762 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:22] Error in run 755: Run already exists in server. Run id(s): {9032839}
[2018-04-11 20:49:22] Started run 763 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:23] Error in run 756: Run already exists in server. Run id(s): {9032829}
[2018-04-11 20:49:23] Started run 764 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:23] Error in run 758: Run already exists in server. Run id(s): {9032849}
[2018-04-11 20:49:23] Started run 765 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:23] Error in run 757: Run already exists in server. Run id(s): {9032846}
[2018-04-11 20:49:23] Started run 766 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:23] Error in run 759: Run already exists in server. Run id(s): {9032871}
[2018-04-11 20:49:23] Started run 767 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:24] Error in run 760: Run already exists in server. Run id(s): {9032877}
[2018-04-11 20:49:24] Started run 768 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:25] Error in run 761: Run already exists in server. Run id(s): {9032901}
[2018-04-11 20:49:25] Started run 769 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:25] Error in run 762: Run already exists in server. Run id(s): {9032889}
[2018-04-11 20:49:25] Started run 770 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:26] Error in run 763: Run already exists in server. Run id(s): {9032888}
[2018-04-11 20:49:26] Started run 771 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:28] Error in run 766: Run already exists in server. Run id(s): {9032899}
[2018-04-11 20:49:28] Error in run 764: Run already exists in server. Run id(s): {9032897}
[2018-04-11 20:49:28] Started run 772 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:28] Started run 773 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:28] Error in run 765: Run already exists in server. Run id(s): {9032930, 9032894}
[2018-04-11 20:49:28] Error in run 767: Run already exists in server. Run id(s): {9032926}
[2018-04-11 20:49:28] Started run 774 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:28] Started run 775 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:28] Error in run 768: Run already exists in server. Run id(s): {9032932}
[2018-04-11 20:49:28] Started run 776 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:29] Error in run 769: Run already exists in server. Run id(s): {9032934}
[2018-04-11 20:49:29] Started run 777 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:30] Error in run 770: Run already exists in server. Run id(s): {9032935}
[2018-04-11 20:49:30] Started run 778 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:31] Error in run 771: Run already exists in server. Run id(s): {9032943}
[2018-04-11 20:49:31] Started run 779 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:32] Error in run 772: Run already exists in server. Run id(s): {9032942}
[2018-04-11 20:49:32] Started run 780 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:32] Error in run 775: Run already exists in server. Run id(s): {9032979}
[2018-04-11 20:49:32] Error in run 774: Run already exists in server. Run id(s): {9032975}
[2018-04-11 20:49:32] Error in run 773: Run already exists in server. Run id(s): {9032939}
[2018-04-11 20:49:32] Started run 781 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:32] Started run 782 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:32] Started run 783 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:33] Error in run 776: Run already exists in server. Run id(s): {9032978}
[2018-04-11 20:49:33] Started run 784 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:34] Error in run 777: Run already exists in server. Run id(s): {9032973}
[2018-04-11 20:49:34] Started run 785 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:34] Error in run 778: Run already exists in server. Run id(s): {9032976}
[2018-04-11 20:49:34] Started run 786 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:36] Error in run 779: Run already exists in server. Run id(s): {9032991}
[2018-04-11 20:49:36] Started run 787 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:37] Error in run 781: Run already exists in server. Run id(s): {9032983}
[2018-04-11 20:49:37] Error in run 780: Run already exists in server. Run id(s): {9032992}
[2018-04-11 20:49:37] Started run 788 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:37] Error in run 782: Run already exists in server. Run id(s): {9033018}
[2018-04-11 20:49:37] Started run 790 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:37] Started run 789 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:37] Error in run 783: Run already exists in server. Run id(s): {9033022}
[2018-04-11 20:49:37] Started run 791 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:37] Error in run 784: Run already exists in server. Run id(s): {9033029}
[2018-04-11 20:49:37] Started run 792 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:38] Error in run 785: Run already exists in server. Run id(s): {9033031}
[2018-04-11 20:49:38] Started run 793 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:39] Error in run 786: Run already exists in server. Run id(s): {9033034}
[2018-04-11 20:49:39] Started run 794 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:40] Error in run 787: Run already exists in server. Run id(s): {9033037}
[2018-04-11 20:49:40] Started run 795 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:41] Error in run 788: Run already exists in server. Run id(s): {9033045}
[2018-04-11 20:49:41] Error in run 790: Run already exists in server. Run id(s): {9033065}
[2018-04-11 20:49:41] Error in run 789: Run already exists in server. Run id(s): {9033038}
[2018-04-11 20:49:41] Started run 796 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:41] Error in run 791: Run already exists in server. Run id(s): {9033060}
[2018-04-11 20:49:41] Started run 799 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:41] Started run 797 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:41] Started run 798 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:42] Error in run 792: Run already exists in server. Run id(s): {9033074}
[2018-04-11 20:49:42] Started run 800 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:43] Error in run 793: Run already exists in server. Run id(s): {9033091}
[2018-04-11 20:49:43] Started run 801 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:43] Error in run 794: Run already exists in server. Run id(s): {9033084}
[2018-04-11 20:49:43] Started run 802 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:45] Error in run 795: Run already exists in server. Run id(s): {9033104}
[2018-04-11 20:49:45] Started run 803 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:46] Error in run 796: Run already exists in server. Run id(s): {9033092}
[2018-04-11 20:49:46] Started run 804 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:46] Error in run 799: Run already exists in server. Run id(s): {9033120}
[2018-04-11 20:49:46] Started run 805 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:46] Error in run 798: Run already exists in server. Run id(s): {9033105}
[2018-04-11 20:49:46] Started run 806 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:46] Error in run 797: Run already exists in server. Run id(s): {9033113}
[2018-04-11 20:49:46] Started run 807 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:46] Error in run 800: Run already exists in server. Run id(s): {9033134}
[2018-04-11 20:49:46] Started run 808 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:47] Error in run 801: Run already exists in server. Run id(s): {9033137}
[2018-04-11 20:49:47] Started run 809 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:48] Error in run 802: Run already exists in server. Run id(s): {9033150}
[2018-04-11 20:49:48] Started run 810 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:49] Error in run 803: Run already exists in server. Run id(s): {9033145}
[2018-04-11 20:49:49] Started run 811 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:50] Error in run 804: Run already exists in server. Run id(s): {9033163}
[2018-04-11 20:49:50] Started run 812 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:50] Error in run 805: Run already exists in server. Run id(s): {9033169}
[2018-04-11 20:49:50] Started run 813 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:50] Error in run 806: Run already exists in server. Run id(s): {9033164}
[2018-04-11 20:49:50] Started run 814 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:50] Error in run 807: Run already exists in server. Run id(s): {9033179}
[2018-04-11 20:49:50] Started run 815 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:51] Error in run 808: Run already exists in server. Run id(s): {9033202}
[2018-04-11 20:49:51] Started run 816 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:52] Error in run 809: Run already exists in server. Run id(s): {9033194}
[2018-04-11 20:49:52] Started run 817 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:52] Error in run 810: Run already exists in server. Run id(s): {9033209}
[2018-04-11 20:49:52] Started run 818 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:54] Error in run 811: Run already exists in server. Run id(s): {9033216}
[2018-04-11 20:49:54] Started run 819 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:55] Error in run 812: Run already exists in server. Run id(s): {9033220}
[2018-04-11 20:49:55] Started run 820 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:55] Error in run 813: Run already exists in server. Run id(s): {9033293}
[2018-04-11 20:49:55] Started run 821 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:55] Error in run 814: Run already exists in server. Run id(s): {9033272}
[2018-04-11 20:49:55] Started run 822 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:55] Error in run 815: Run already exists in server. Run id(s): {9033291}
[2018-04-11 20:49:55] Started run 823 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:55] Error in run 816: Run already exists in server. Run id(s): {9033246}
[2018-04-11 20:49:55] Started run 824 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:57] Error in run 817: Run already exists in server. Run id(s): {9033243}
[2018-04-11 20:49:57] Started run 825 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:57] Error in run 818: Run already exists in server. Run id(s): {9033251}
[2018-04-11 20:49:57] Started run 826 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:59] Error in run 819: Run already exists in server. Run id(s): {9033255}
[2018-04-11 20:49:59] Started run 827 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:59] Error in run 820: Run already exists in server. Run id(s): {9033259}
[2018-04-11 20:49:59] Started run 828 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:59] Error in run 821: Run already exists in server. Run id(s): {9033282}
[2018-04-11 20:49:59] Started run 829 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:59] Error in run 822: Run already exists in server. Run id(s): {9033295}
[2018-04-11 20:49:59] Started run 830 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:49:59] Error in run 823: Run already exists in server. Run id(s): {9033297}
[2018-04-11 20:49:59] Started run 831 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:00] Error in run 824: Run already exists in server. Run id(s): {9033324}
[2018-04-11 20:50:00] Started run 832 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:01] Error in run 825: Run already exists in server. Run id(s): {9033314}
[2018-04-11 20:50:01] Started run 833 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:01] Error in run 826: Run already exists in server. Run id(s): {9033332}
[2018-04-11 20:50:01] Started run 834 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:03] Error in run 827: Run already exists in server. Run id(s): {9033334}
[2018-04-11 20:50:03] Started run 835 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:04] Error in run 829: Run already exists in server. Run id(s): {9033342}
[2018-04-11 20:50:04] Error in run 828: Run already exists in server. Run id(s): {9033340}
[2018-04-11 20:50:04] Started run 837 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:04] Started run 836 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:04] Error in run 831: Run already exists in server. Run id(s): {9033351}
[2018-04-11 20:50:04] Error in run 830: Run already exists in server. Run id(s): {9033343}
[2018-04-11 20:50:04] Started run 838 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:04] Started run 839 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:04] Error in run 832: Run already exists in server. Run id(s): {9033362}
[2018-04-11 20:50:04] Started run 840 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:06] Error in run 833: Run already exists in server. Run id(s): {9033371}
[2018-04-11 20:50:06] Started run 841 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:06] Error in run 834: Run already exists in server. Run id(s): {9033387}
[2018-04-11 20:50:06] Started run 842 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:08] Error in run 835: Run already exists in server. Run id(s): {9033386}
[2018-04-11 20:50:08] Started run 843 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:08] Error in run 836: Run already exists in server. Run id(s): {9033379}
[2018-04-11 20:50:08] Started run 844 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:08] Error in run 837: Run already exists in server. Run id(s): {9033385}
[2018-04-11 20:50:08] Started run 845 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:09] Error in run 839: Run already exists in server. Run id(s): {9033388}
[2018-04-11 20:50:09] Error in run 838: Run already exists in server. Run id(s): {9033400}
[2018-04-11 20:50:09] Started run 846 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:09] Started run 847 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:09] Error in run 840: Run already exists in server. Run id(s): {9033402}
[2018-04-11 20:50:09] Started run 848 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:10] Error in run 841: Run already exists in server. Run id(s): {9033414}
[2018-04-11 20:50:10] Started run 849 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:10] Error in run 842: Run already exists in server. Run id(s): {9033429}
[2018-04-11 20:50:10] Started run 850 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:12] Error in run 843: Run already exists in server. Run id(s): {9033449}
[2018-04-11 20:50:12] Started run 851 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:13] Error in run 845: Run already exists in server. Run id(s): {9033435}
[2018-04-11 20:50:13] Error in run 844: Run already exists in server. Run id(s): {9033441}
[2018-04-11 20:50:13] Started run 852 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:13] Started run 853 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:13] Error in run 847: Run already exists in server. Run id(s): {9033456}
[2018-04-11 20:50:13] Started run 854 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:13] Error in run 848: Run already exists in server. Run id(s): {9033453}
[2018-04-11 20:50:13] Started run 855 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:13] Error in run 846: Run already exists in server. Run id(s): {9033438}
[2018-04-11 20:50:13] Started run 856 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:15] Error in run 849: Run already exists in server. Run id(s): {9033454}
[2018-04-11 20:50:15] Started run 857 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:15] Error in run 850: Run already exists in server. Run id(s): {9033476}
[2018-04-11 20:50:15] Started run 858 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:17] Error in run 851: Run already exists in server. Run id(s): {9033483}
[2018-04-11 20:50:17] Started run 859 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:17] Error in run 852: Run already exists in server. Run id(s): {9033482}
[2018-04-11 20:50:17] Error in run 853: Run already exists in server. Run id(s): {9033488}
[2018-04-11 20:50:17] Started run 860 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:17] Started run 861 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:18] Error in run 854: Run already exists in server. Run id(s): {9033515}
[2018-04-11 20:50:18] Started run 862 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:18] Error in run 855: Run already exists in server. Run id(s): {9033504}
[2018-04-11 20:50:18] Started run 863 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:18] Error in run 856: Run already exists in server. Run id(s): {9033506}
[2018-04-11 20:50:18] Started run 864 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:19] Error in run 857: Run already exists in server. Run id(s): {9033501}
[2018-04-11 20:50:19] Started run 865 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:20] Error in run 858: Run already exists in server. Run id(s): {9033523}
[2018-04-11 20:50:20] Started run 866 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:21] Error in run 859: Run already exists in server. Run id(s): {9033526}
[2018-04-11 20:50:21] Started run 867 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:22] Error in run 861: Run already exists in server. Run id(s): {9033533}
[2018-04-11 20:50:22] Error in run 860: Run already exists in server. Run id(s): {9033527}
[2018-04-11 20:50:22] Started run 868 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:22] Started run 869 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:22] Error in run 862: Run already exists in server. Run id(s): {9033563}
[2018-04-11 20:50:22] Started run 870 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:22] Error in run 863: Run already exists in server. Run id(s): {9033561}
[2018-04-11 20:50:22] Started run 871 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:23] Error in run 864: Run already exists in server. Run id(s): {9033576}
[2018-04-11 20:50:23] Started run 872 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:24] Error in run 865: Run already exists in server. Run id(s): {9033578}
[2018-04-11 20:50:24] Started run 873 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:24] Error in run 866: Run already exists in server. Run id(s): {9033568}
[2018-04-11 20:50:24] Started run 874 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:26] Error in run 867: Run already exists in server. Run id(s): {9033580}
[2018-04-11 20:50:26] Started run 875 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:27] Error in run 869: Run already exists in server. Run id(s): {9033626}
[2018-04-11 20:50:27] Started run 876 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:27] Error in run 868: Run already exists in server. Run id(s): {9033575}
[2018-04-11 20:50:27] Started run 877 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:27] Error in run 870: Run already exists in server. Run id(s): {9033621}
[2018-04-11 20:50:27] Started run 878 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:27] Error in run 871: Run already exists in server. Run id(s): {9033631}
[2018-04-11 20:50:27] Started run 879 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:27] Error in run 872: Run already exists in server. Run id(s): {9033623}
[2018-04-11 20:50:27] Started run 880 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:28] Error in run 873: Run already exists in server. Run id(s): {9033625}
[2018-04-11 20:50:28] Started run 881 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:29] Error in run 874: Run already exists in server. Run id(s): {9033630}
[2018-04-11 20:50:29] Started run 882 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:30] Error in run 875: Run already exists in server. Run id(s): {9033637}
[2018-04-11 20:50:30] Started run 883 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:31] Error in run 876: Run already exists in server. Run id(s): {9033639}
[2018-04-11 20:50:31] Started run 884 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:31] Error in run 878: Run already exists in server. Run id(s): {9033685}
[2018-04-11 20:50:31] Started run 885 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:31] Error in run 877: Run already exists in server. Run id(s): {9033678}
[2018-04-11 20:50:31] Started run 886 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:31] Error in run 879: Run already exists in server. Run id(s): {9033681}
[2018-04-11 20:50:31] Started run 887 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:32] Error in run 880: Run already exists in server. Run id(s): {9033695}
[2018-04-11 20:50:32] Started run 888 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:33] Error in run 881: Run already exists in server. Run id(s): {9033680}
[2018-04-11 20:50:33] Started run 889 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:34] Error in run 882: Run already exists in server. Run id(s): {9033684}
[2018-04-11 20:50:34] Started run 890 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:35] Error in run 883: Run already exists in server. Run id(s): {9033711}
[2018-04-11 20:50:35] Started run 891 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:36] Error in run 884: Run already exists in server. Run id(s): {9033692}
[2018-04-11 20:50:36] Started run 892 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:36] Error in run 885: Run already exists in server. Run id(s): {9033744}
[2018-04-11 20:50:36] Error in run 886: Run already exists in server. Run id(s): {9033730}
[2018-04-11 20:50:36] Started run 893 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:36] Started run 894 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:36] Error in run 887: Run already exists in server. Run id(s): {9033735}
[2018-04-11 20:50:36] Started run 895 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:36] Error in run 888: Run already exists in server. Run id(s): {9033728}
[2018-04-11 20:50:36] Started run 896 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:38] Error in run 889: Run already exists in server. Run id(s): {9033727}
[2018-04-11 20:50:38] Started run 897 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:38] Error in run 890: Run already exists in server. Run id(s): {9033747}
[2018-04-11 20:50:38] Started run 898 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:39] Error in run 891: Run already exists in server. Run id(s): {9033750}
[2018-04-11 20:50:39] Started run 899 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:40] Error in run 892: Run already exists in server. Run id(s): {9033764}
[2018-04-11 20:50:40] Started run 900 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:40] Error in run 893: Run already exists in server. Run id(s): {9033776}
[2018-04-11 20:50:40] Started run 901 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:40] Error in run 894: Run already exists in server. Run id(s): {9033782}
[2018-04-11 20:50:40] Started run 902 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:41] Error in run 895: Run already exists in server. Run id(s): {9033814}
[2018-04-11 20:50:41] Started run 903 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:41] Error in run 896: Run already exists in server. Run id(s): {9033783}
[2018-04-11 20:50:41] Started run 904 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:42] Error in run 897: Run already exists in server. Run id(s): {9033803}
[2018-04-11 20:50:42] Started run 905 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:43] Error in run 898: Run already exists in server. Run id(s): {9033795}
[2018-04-11 20:50:43] Started run 906 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:44] Error in run 899: Run already exists in server. Run id(s): {9033819}
[2018-04-11 20:50:44] Started run 907 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:45] Error in run 900: Run already exists in server. Run id(s): {9033817}
[2018-04-11 20:50:45] Started run 908 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:45] Error in run 901: Run already exists in server. Run id(s): {9033835}
[2018-04-11 20:50:45] Started run 909 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:45] Error in run 902: Run already exists in server. Run id(s): {9033834}
[2018-04-11 20:50:45] Started run 910 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:45] Error in run 903: Run already exists in server. Run id(s): {9033833}
[2018-04-11 20:50:45] Started run 911 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:45] Error in run 904: Run already exists in server. Run id(s): {9033854}
[2018-04-11 20:50:45] Started run 912 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:47] Error in run 905: Run already exists in server. Run id(s): {9033862}
[2018-04-11 20:50:47] Started run 913 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:47] Error in run 906: Run already exists in server. Run id(s): {9033884}
[2018-04-11 20:50:47] Started run 914 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:48] Error in run 907: Run already exists in server. Run id(s): {9033863}
[2018-04-11 20:50:48] Started run 915 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:49] Error in run 908: Run already exists in server. Run id(s): {9033873}
[2018-04-11 20:50:49] Started run 916 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:49] Error in run 909: Run already exists in server. Run id(s): {9033893}
[2018-04-11 20:50:49] Started run 917 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:49] Error in run 910: Run already exists in server. Run id(s): {9033877}
[2018-04-11 20:50:49] Started run 918 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:50] Error in run 911: Run already exists in server. Run id(s): {9033890}
[2018-04-11 20:50:50] Started run 919 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:50] Error in run 912: Run already exists in server. Run id(s): {9033902}
[2018-04-11 20:50:50] Started run 920 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:51] Error in run 913: Run already exists in server. Run id(s): {9033906}
[2018-04-11 20:50:51] Started run 921 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:52] Error in run 914: Run already exists in server. Run id(s): {9033933}
[2018-04-11 20:50:52] Started run 922 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:53] Error in run 915: Run already exists in server. Run id(s): {9033934}
[2018-04-11 20:50:53] Started run 923 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:54] Error in run 916: Run already exists in server. Run id(s): {9033967}
[2018-04-11 20:50:54] Started run 924 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:54] Error in run 917: Run already exists in server. Run id(s): {9033937}
[2018-04-11 20:50:54] Started run 925 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:54] Error in run 918: Run already exists in server. Run id(s): {9033943}
[2018-04-11 20:50:54] Started run 926 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:54] Error in run 919: Run already exists in server. Run id(s): {9033945}
[2018-04-11 20:50:54] Started run 927 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:54] Error in run 920: Run already exists in server. Run id(s): {9033955}
[2018-04-11 20:50:54] Started run 928 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:56] Error in run 921: Run already exists in server. Run id(s): {9033962}
[2018-04-11 20:50:56] Started run 929 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:56] Error in run 922: Run already exists in server. Run id(s): {9033989}
[2018-04-11 20:50:56] Started run 930 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:57] Error in run 923: Run already exists in server. Run id(s): {9033984}
[2018-04-11 20:50:57] Started run 931 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:58] Error in run 924: Run already exists in server. Run id(s): {9033992}
[2018-04-11 20:50:58] Started run 932 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:58] Error in run 925: Run already exists in server. Run id(s): {9033998}
[2018-04-11 20:50:58] Started run 933 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:59] Error in run 926: Run already exists in server. Run id(s): {9034001}
[2018-04-11 20:50:59] Error in run 927: Run already exists in server. Run id(s): {9034019}
[2018-04-11 20:50:59] Started run 934 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:59] Started run 935 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:50:59] Error in run 928: Run already exists in server. Run id(s): {9034028}
[2018-04-11 20:50:59] Started run 936 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:00] Error in run 929: Run already exists in server. Run id(s): {9034044}
[2018-04-11 20:51:00] Started run 937 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:01] Error in run 930: Run already exists in server. Run id(s): {9034045}
[2018-04-11 20:51:01] Started run 938 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:02] Error in run 931: Run already exists in server. Run id(s): {9034059}
[2018-04-11 20:51:02] Started run 939 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:03] Error in run 932: Run already exists in server. Run id(s): {9034054}
[2018-04-11 20:51:03] Started run 940 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:03] Error in run 933: Run already exists in server. Run id(s): {9034065}
[2018-04-11 20:51:03] Started run 941 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:03] Error in run 935: Run already exists in server. Run id(s): {9034073}
[2018-04-11 20:51:03] Started run 942 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:03] Error in run 934: Run already exists in server. Run id(s): {9034063}
[2018-04-11 20:51:03] Started run 943 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:03] Error in run 936: Run already exists in server. Run id(s): {9034077}
[2018-04-11 20:51:03] Started run 944 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:05] Error in run 937: Run already exists in server. Run id(s): {9034080}
[2018-04-11 20:51:05] Started run 945 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:06] Error in run 938: Run already exists in server. Run id(s): {9034092}
[2018-04-11 20:51:06] Started run 946 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:07] Error in run 939: Run already exists in server. Run id(s): {9034095}
[2018-04-11 20:51:07] Started run 947 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:07] Error in run 941: Run already exists in server. Run id(s): {9034104}
[2018-04-11 20:51:07] Error in run 940: Run already exists in server. Run id(s): {9034122}
[2018-04-11 20:51:07] Started run 948 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:07] Started run 949 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:08] Error in run 942: Run already exists in server. Run id(s): {9034108}
[2018-04-11 20:51:08] Error in run 944: Run already exists in server. Run id(s): {9034105}
[2018-04-11 20:51:08] Started run 950 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:08] Error in run 943: Run already exists in server. Run id(s): {9034098}
[2018-04-11 20:51:08] Started run 951 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:08] Started run 952 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:10] Error in run 945: Run already exists in server. Run id(s): {9034115}
[2018-04-11 20:51:10] Started run 953 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:10] Error in run 946: Run already exists in server. Run id(s): {9034142}
[2018-04-11 20:51:10] Started run 954 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:11] Error in run 947: Run already exists in server. Run id(s): {9034139}
[2018-04-11 20:51:11] Started run 955 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:12] Error in run 949: Run already exists in server. Run id(s): {9034154}
[2018-04-11 20:51:12] Started run 956 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:12] Error in run 948: Run already exists in server. Run id(s): {9034155}
[2018-04-11 20:51:12] Started run 957 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:13] Error in run 950: Run already exists in server. Run id(s): {9034191}
[2018-04-11 20:51:13] Started run 958 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:13] Error in run 952: Run already exists in server. Run id(s): {9034175}
[2018-04-11 20:51:13] Started run 959 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:13] Error in run 951: Run already exists in server. Run id(s): {9034161}
[2018-04-11 20:51:13] Started run 960 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:14] Error in run 953: Run already exists in server. Run id(s): {9034176}
[2018-04-11 20:51:14] Started run 961 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:15] Error in run 954: Run already exists in server. Run id(s): {9034189}
[2018-04-11 20:51:15] Started run 962 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:16] Error in run 955: Run already exists in server. Run id(s): {9034190}
[2018-04-11 20:51:16] Started run 963 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:17] Error in run 956: Run already exists in server. Run id(s): {9034199}
[2018-04-11 20:51:17] Started run 964 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:17] Error in run 957: Run already exists in server. Run id(s): {9034200}
[2018-04-11 20:51:17] Started run 965 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:17] Error in run 958: Run already exists in server. Run id(s): {9034206}
[2018-04-11 20:51:17] Started run 966 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:17] Error in run 959: Run already exists in server. Run id(s): {9034205}
[2018-04-11 20:51:17] Started run 967 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:17] Error in run 960: Run already exists in server. Run id(s): {9034201}
[2018-04-11 20:51:17] Started run 968 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:19] Error in run 961: Run already exists in server. Run id(s): {9034234}
[2018-04-11 20:51:19] Started run 969 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:20] Error in run 962: Run already exists in server. Run id(s): {9034244}
[2018-04-11 20:51:20] Started run 970 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:20] Error in run 963: Run already exists in server. Run id(s): {9034227}
[2018-04-11 20:51:20] Started run 971 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:21] Error in run 965: Run already exists in server. Run id(s): {9034251}
[2018-04-11 20:51:21] Started run 972 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:21] Error in run 964: Run already exists in server. Run id(s): {9034250}
[2018-04-11 20:51:21] Started run 973 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:21] Error in run 966: Run already exists in server. Run id(s): {9034248}
[2018-04-11 20:51:21] Started run 974 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:22] Error in run 967: Run already exists in server. Run id(s): {9034253}
[2018-04-11 20:51:22] Started run 975 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:22] Error in run 968: Run already exists in server. Run id(s): {9034257}
[2018-04-11 20:51:22] Started run 976 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:23] Error in run 969: Run already exists in server. Run id(s): {9034277}
[2018-04-11 20:51:23] Started run 977 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:24] Error in run 970: Run already exists in server. Run id(s): {9034283}
[2018-04-11 20:51:24] Started run 978 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:25] Error in run 971: Run already exists in server. Run id(s): {9034291}
[2018-04-11 20:51:25] Started run 979 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:26] Error in run 972: Run already exists in server. Run id(s): {9034292}
[2018-04-11 20:51:26] Started run 980 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:26] Error in run 973: Run already exists in server. Run id(s): {9034290}
[2018-04-11 20:51:26] Started run 981 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:26] Error in run 974: Run already exists in server. Run id(s): {9034307}
[2018-04-11 20:51:26] Started run 982 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:26] Error in run 975: Run already exists in server. Run id(s): {9034301}
[2018-04-11 20:51:26] Started run 983 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:26] Error in run 976: Run already exists in server. Run id(s): {9034304}
[2018-04-11 20:51:26] Started run 984 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:28] Error in run 977: Run already exists in server. Run id(s): {9034328}
[2018-04-11 20:51:28] Started run 985 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:29] Error in run 978: Run already exists in server. Run id(s): {9034339}
[2018-04-11 20:51:29] Started run 986 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:29] Error in run 979: Run already exists in server. Run id(s): {9034337}
[2018-04-11 20:51:29] Started run 987 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:30] Error in run 980: Run already exists in server. Run id(s): {9034360}
[2018-04-11 20:51:30] Started run 988 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:30] Error in run 981: Run already exists in server. Run id(s): {9034338}
[2018-04-11 20:51:30] Started run 989 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:31] Error in run 982: Run already exists in server. Run id(s): {9034344}
[2018-04-11 20:51:31] Started run 990 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:31] Error in run 983: Run already exists in server. Run id(s): {9034352}
[2018-04-11 20:51:31] Started run 991 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:31] Error in run 984: Run already exists in server. Run id(s): {9034350}
[2018-04-11 20:51:31] Started run 992 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:32] Error in run 985: Run already exists in server. Run id(s): {9034364}
[2018-04-11 20:51:32] Started run 993 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:33] Error in run 986: Run already exists in server. Run id(s): {9034389}
[2018-04-11 20:51:33] Started run 994 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:34] Error in run 987: Run already exists in server. Run id(s): {9034395}
[2018-04-11 20:51:34] Started run 995 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:35] Error in run 988: Run already exists in server. Run id(s): {9034396}
[2018-04-11 20:51:35] Started run 996 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:35] Error in run 989: Run already exists in server. Run id(s): {9034409}
[2018-04-11 20:51:35] Started run 997 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:35] Error in run 991: Run already exists in server. Run id(s): {9034402}
[2018-04-11 20:51:36] Error in run 990: Run already exists in server. Run id(s): {9034401}
[2018-04-11 20:51:35] Started run 998 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:36] Started run 999 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:36] Error in run 992: Run already exists in server. Run id(s): {9034405}
[2018-04-11 20:51:36] Started run 1000 on task 10093, dataset 'banknote-authentication'.
[2018-04-11 20:51:37] Error in run 993: Run already exists in server. Run id(s): {9034436}
[2018-04-11 20:51:38] Error in run 994: Run already exists in server. Run id(s): {9034449}
[2018-04-11 20:51:39] Error in run 995: Run already exists in server. Run id(s): {9034459}
[2018-04-11 20:51:39] Error in run 996: Run already exists in server. Run id(s): {9034455}
[2018-04-11 20:51:40] Error in run 997: Run already exists in server. Run id(s): {9034462}
[2018-04-11 20:51:40] Error in run 999: Run already exists in server. Run id(s): {9034465}
[2018-04-11 20:51:40] Error in run 998: Run already exists in server. Run id(s): {9034464}
[2018-04-11 20:51:40] Error in run 1000: Run already exists in server. Run id(s): {9034471}
